/******************************************************************************
** demo_nodemanagerdemo.h
**
**   **************************** auto-generated ****************************
**     This code was generated by a tool: UaModeler
**     Runtime Version: 1.5.0, using C++ OPC UA SDK 1.5.0 template (version 4)
**
**     This is a template file that was generated for your convenience.
**     This file will not be overwritten when generating code again.
**     ADD YOUR IMPLEMTATION HERE!
**   **************************** auto-generated ****************************
**
** Copyright (c) 2006-2016 Unified Automation GmbH. All rights reserved.
**
** Software License Agreement ("SLA") Version 2.5
**
** Unless explicitly acquired and licensed from Licensor under another
** license, the contents of this file are subject to the Software License
** Agreement ("SLA") Version 2.5, or subsequent versions
** as allowed by the SLA, and You may not copy or use this file in either
** source code or executable form, except in compliance with the terms and
** conditions of the SLA.
**
** All software distributed under the SLA is provided strictly on an
** "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED,
** AND LICENSOR HEREBY DISCLAIMS ALL SUCH WARRANTIES, INCLUDING WITHOUT
** LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
** PURPOSE, QUIET ENJOYMENT, OR NON-INFRINGEMENT. See the SLA for specific
** language governing rights and limitations under the SLA.
**
** The complete license agreement can be found here:
** http://unifiedautomation.com/License/SLA/2.5/
**
** Project: C++ OPC Server SDK information model for namespace http://cs.hs-rm.de/mierswa_thesis/3AchsenEMCNCLaserSchneid/
**
** Description: OPC Unified Architecture Software Development Kit.
**
** Created: 19.08.2016
**
******************************************************************************/

#ifndef _DEMO_NODEMANAGERDEMO_H__
#define _DEMO_NODEMANAGERDEMO_H__

#include "demo_nodemanagerdemobase.h"

#include <adapter/adapter.h>

#include <map>
#include <memory>

/** Namespace for the UA information model http://cs.hs-rm.de/mierswa_thesis/3AchsenEMCNCLaserSchneid/
*/
namespace Demo {

/** NodeManager for Demo information model.
 *
 *  This class is used to add custom implementation.
 *  The base class NodeManagerDemoBase contains the auto generated code for creating the adress space.
 */
class UAMODELS_EXPORT NodeManagerDemo : public NodeManagerDemoBase, UaThread
{
    UA_DISABLE_COPY(NodeManagerDemo);
    NodeManagerDemo();
public:
    /* construction / destruction */
    NodeManagerDemo(std::shared_ptr<adapter::adapter> adapter, OpcUa_Boolean firesEvents, OpcUa_Int32 nHashTableSize = 10007);
    virtual ~NodeManagerDemo();

    //- Interface NodeManagerUaNode -------------------------------------------------------
    virtual UaStatus   afterStartUp();
    virtual UaStatus   beforeShutDown();
    //- Interface NodeManagerUaNode -------------------------------------------------------

    void setup_nodes(adapter::xml_node_map_type const &nodes, std::string const &browse_path = "");
    void setup_node(adapter::xml_node_type const &node, UaNode *uaNode);
    void set_variable_from_node(adapter::xml_node_type const &node, UaVariable *variable, adapter::xml_node_fetch_info_type const &fetch_info);
    void run();

private:
    std::shared_ptr<adapter::adapter> adapter_;
    std::map<adapter::xml_node_type const *, adapter::xml_node_type const *> mirrored_nodes_;
    std::map<adapter::xml_node_type const *, UaNodeId> nodes_;

};

} // End namespace for the UA information model http://cs.hs-rm.de/mierswa_thesis/3AchsenEMCNCLaserSchneid/

#endif // #ifndef __NODEMANAGERDEMO_H__

