/******************************************************************************
** demo_identifiers.h
**
**   **************************** auto-generated ****************************
**     This code was generated by a tool: UaModeler
**     Runtime Version: 1.5.0, using C++ OPC UA SDK 1.5.0 template (version 4)
**
**     Changes to this file may cause incorrect behavior and will be lost if
**     the code is regenerated.
**   **************************** auto-generated ****************************
**
** Copyright (c) 2006-2016 Unified Automation GmbH. All rights reserved.
**
** Software License Agreement ("SLA") Version 2.5
**
** Unless explicitly acquired and licensed from Licensor under another
** license, the contents of this file are subject to the Software License
** Agreement ("SLA") Version 2.5, or subsequent versions
** as allowed by the SLA, and You may not copy or use this file in either
** source code or executable form, except in compliance with the terms and
** conditions of the SLA.
**
** All software distributed under the SLA is provided strictly on an
** "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED,
** AND LICENSOR HEREBY DISCLAIMS ALL SUCH WARRANTIES, INCLUDING WITHOUT
** LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
** PURPOSE, QUIET ENJOYMENT, OR NON-INFRINGEMENT. See the SLA for specific
** language governing rights and limitations under the SLA.
**
** The complete license agreement can be found here:
** http://unifiedautomation.com/License/SLA/2.5/
**
** Project: C++ OPC Server SDK information model for namespace http://cs.hs-rm.de/mierswa_thesis/3AchsenEMCNCLaserSchneid/
**
** Description: OPC Unified Architecture Software Development Kit.
**
** Created: 19.08.2016
**
******************************************************************************/

#ifndef __DEMO_IDENTIFIERS_H__
#define __DEMO_IDENTIFIERS_H__

#define Demo_NameSpaceUri "http://cs.hs-rm.de/mierswa_thesis/3AchsenEMCNCLaserSchneid/"

#include "version_coremodule.h"
#if (PROD_MAJOR != 1 || (PROD_MAJOR == 1 && PROD_MINOR < 5) || (PROD_MAJOR == 1 && PROD_MINOR == 5 && PROD_MINOR2 < 0))
#if ! (PROD_MAJOR == 1 && PROD_MINOR == 3 && PROD_MINOR2 == 0 && CPP_SDK_BUILD == 193)
#error The code is generated for SDK version 1.5.0
#endif
#endif

/*============================================================================
* ObjectType Identifiers
 *===========================================================================*/

/*============================================================================
* VariableType Identifiers
 *===========================================================================*/

/*============================================================================
* DataType Identifiers
 *===========================================================================*/

/*============================================================================
* ReferenceType Identifiers
 *===========================================================================*/

/*============================================================================
* Object Identifiers
 *===========================================================================*/
#define DemoId_CncInterface_CncAxisList_X 5015
#define DemoId_CncInterface_CncAxisList_Y 5016
#define DemoId_CncInterface_CncAxisList_Z 5017
#define DemoId_CncInterface_CncChannelList_Channel1 5018

/*============================================================================
* Variable Identifiers
 *===========================================================================*/
#define DemoId_CncInterface_CncAxisList_X_ActChannel 6018
#define DemoId_CncInterface_CncAxisList_X_ActLoad 6019
#define DemoId_CncInterface_CncAxisList_X_ActLoad_EURange 6020
#define DemoId_CncInterface_CncAxisList_X_ActPower 6021
#define DemoId_CncInterface_CncAxisList_X_ActPower_EURange 6022
#define DemoId_CncInterface_CncAxisList_X_ActStatus 6001
#define DemoId_CncInterface_CncAxisList_X_ActTorque 6023
#define DemoId_CncInterface_CncAxisList_X_ActTorque_EURange 6024
#define DemoId_CncInterface_CncAxisList_X_CmdTorque 6025
#define DemoId_CncInterface_CncAxisList_X_CmdTorque_EURange 6026
#define DemoId_CncInterface_CncAxisList_X_IsInactive 6027
#define DemoId_CncInterface_CncAxisList_X_IsReferenced 6002
#define DemoId_CncInterface_CncAxisList_X_IsRotational 6003
#define DemoId_CncInterface_CncAxisList_X_IsVirtual 6028
#define DemoId_CncInterface_CncAxisList_X_PosDirect 6004
#define DemoId_CncInterface_CncAxisList_X_PosDirect_ActPos 6005
#define DemoId_CncInterface_CncAxisList_X_PosDirect_CmdPos 6006
#define DemoId_CncInterface_CncAxisList_X_PosDirect_EngineeringUnits 6007
#define DemoId_CncInterface_CncAxisList_X_PosDirect_EURange 6008
#define DemoId_CncInterface_CncAxisList_X_PosDirect_RemDist 6009
#define DemoId_CncInterface_CncAxisList_X_PosIndirect 6010
#define DemoId_CncInterface_CncAxisList_X_PosIndirect_ActPos 6011
#define DemoId_CncInterface_CncAxisList_X_PosIndirect_CmdPos 6012
#define DemoId_CncInterface_CncAxisList_X_PosIndirect_EngineeringUnits 6013
#define DemoId_CncInterface_CncAxisList_X_PosIndirect_EURange 6014
#define DemoId_CncInterface_CncAxisList_X_PosIndirect_RemDist 6015
#define DemoId_CncInterface_CncAxisList_X_ZeroOffset 6016
#define DemoId_CncInterface_CncAxisList_X_ZeroOffset_EURange 6017
#define DemoId_CncInterface_CncAxisList_Y_ActChannel 6046
#define DemoId_CncInterface_CncAxisList_Y_ActLoad 6047
#define DemoId_CncInterface_CncAxisList_Y_ActLoad_EURange 6048
#define DemoId_CncInterface_CncAxisList_Y_ActPower 6049
#define DemoId_CncInterface_CncAxisList_Y_ActPower_EURange 6050
#define DemoId_CncInterface_CncAxisList_Y_ActStatus 6029
#define DemoId_CncInterface_CncAxisList_Y_ActTorque 6051
#define DemoId_CncInterface_CncAxisList_Y_ActTorque_EURange 6052
#define DemoId_CncInterface_CncAxisList_Y_CmdTorque 6053
#define DemoId_CncInterface_CncAxisList_Y_CmdTorque_EURange 6054
#define DemoId_CncInterface_CncAxisList_Y_IsInactive 6055
#define DemoId_CncInterface_CncAxisList_Y_IsReferenced 6030
#define DemoId_CncInterface_CncAxisList_Y_IsRotational 6031
#define DemoId_CncInterface_CncAxisList_Y_IsVirtual 6056
#define DemoId_CncInterface_CncAxisList_Y_PosDirect 6032
#define DemoId_CncInterface_CncAxisList_Y_PosDirect_ActPos 6033
#define DemoId_CncInterface_CncAxisList_Y_PosDirect_CmdPos 6034
#define DemoId_CncInterface_CncAxisList_Y_PosDirect_EngineeringUnits 6035
#define DemoId_CncInterface_CncAxisList_Y_PosDirect_EURange 6036
#define DemoId_CncInterface_CncAxisList_Y_PosDirect_RemDist 6037
#define DemoId_CncInterface_CncAxisList_Y_PosIndirect 6038
#define DemoId_CncInterface_CncAxisList_Y_PosIndirect_ActPos 6039
#define DemoId_CncInterface_CncAxisList_Y_PosIndirect_CmdPos 6040
#define DemoId_CncInterface_CncAxisList_Y_PosIndirect_EngineeringUnits 6041
#define DemoId_CncInterface_CncAxisList_Y_PosIndirect_EURange 6042
#define DemoId_CncInterface_CncAxisList_Y_PosIndirect_RemDist 6043
#define DemoId_CncInterface_CncAxisList_Y_ZeroOffset 6044
#define DemoId_CncInterface_CncAxisList_Y_ZeroOffset_EURange 6045
#define DemoId_CncInterface_CncAxisList_Z_ActChannel 6074
#define DemoId_CncInterface_CncAxisList_Z_ActLoad 6075
#define DemoId_CncInterface_CncAxisList_Z_ActLoad_EURange 6076
#define DemoId_CncInterface_CncAxisList_Z_ActPower 6077
#define DemoId_CncInterface_CncAxisList_Z_ActPower_EURange 6078
#define DemoId_CncInterface_CncAxisList_Z_ActStatus 6057
#define DemoId_CncInterface_CncAxisList_Z_ActTorque 6079
#define DemoId_CncInterface_CncAxisList_Z_ActTorque_EURange 6080
#define DemoId_CncInterface_CncAxisList_Z_CmdTorque 6081
#define DemoId_CncInterface_CncAxisList_Z_CmdTorque_EURange 6082
#define DemoId_CncInterface_CncAxisList_Z_IsInactive 6083
#define DemoId_CncInterface_CncAxisList_Z_IsReferenced 6058
#define DemoId_CncInterface_CncAxisList_Z_IsRotational 6059
#define DemoId_CncInterface_CncAxisList_Z_IsVirtual 6084
#define DemoId_CncInterface_CncAxisList_Z_PosDirect 6060
#define DemoId_CncInterface_CncAxisList_Z_PosDirect_ActPos 6061
#define DemoId_CncInterface_CncAxisList_Z_PosDirect_CmdPos 6062
#define DemoId_CncInterface_CncAxisList_Z_PosDirect_EngineeringUnits 6063
#define DemoId_CncInterface_CncAxisList_Z_PosDirect_EURange 6064
#define DemoId_CncInterface_CncAxisList_Z_PosDirect_RemDist 6065
#define DemoId_CncInterface_CncAxisList_Z_PosIndirect 6066
#define DemoId_CncInterface_CncAxisList_Z_PosIndirect_ActPos 6067
#define DemoId_CncInterface_CncAxisList_Z_PosIndirect_CmdPos 6068
#define DemoId_CncInterface_CncAxisList_Z_PosIndirect_EngineeringUnits 6069
#define DemoId_CncInterface_CncAxisList_Z_PosIndirect_EURange 6070
#define DemoId_CncInterface_CncAxisList_Z_PosIndirect_RemDist 6071
#define DemoId_CncInterface_CncAxisList_Z_ZeroOffset 6072
#define DemoId_CncInterface_CncAxisList_Z_ZeroOffset_EURange 6073
#define DemoId_CncInterface_CncChannelList_Channel1_ActFeedrate 6085
#define DemoId_CncInterface_CncChannelList_Channel1_ActFeedrate_EURange 6086
#define DemoId_CncInterface_CncChannelList_Channel1_ActGFunctions 6087
#define DemoId_CncInterface_CncChannelList_Channel1_ActJogIncrement 6088
#define DemoId_CncInterface_CncChannelList_Channel1_ActJogIncrement_EURange 6089
#define DemoId_CncInterface_CncChannelList_Channel1_ActMainProgramFile 6090
#define DemoId_CncInterface_CncChannelList_Channel1_ActMainProgramFileOffset 6091
#define DemoId_CncInterface_CncChannelList_Channel1_ActMainProgramLine 6092
#define DemoId_CncInterface_CncChannelList_Channel1_ActMainProgramName 6093
#define DemoId_CncInterface_CncChannelList_Channel1_ActMFunctions 6094
#define DemoId_CncInterface_CncChannelList_Channel1_ActModalOffsetFunction 6095
#define DemoId_CncInterface_CncChannelList_Channel1_ActOperationMode 6096
#define DemoId_CncInterface_CncChannelList_Channel1_ActOverride 6097
#define DemoId_CncInterface_CncChannelList_Channel1_ActOverride_EURange 6098
#define DemoId_CncInterface_CncChannelList_Channel1_ActProgramBlock 6099
#define DemoId_CncInterface_CncChannelList_Channel1_ActProgramFile 6100
#define DemoId_CncInterface_CncChannelList_Channel1_ActProgramFileOffset 6101
#define DemoId_CncInterface_CncChannelList_Channel1_ActProgramLine 6102
#define DemoId_CncInterface_CncChannelList_Channel1_ActProgramName 6103
#define DemoId_CncInterface_CncChannelList_Channel1_ActProgramStatus 6104
#define DemoId_CncInterface_CncChannelList_Channel1_ActStatus 6105
#define DemoId_CncInterface_CncChannelList_Channel1_BlockMode 6106
#define DemoId_CncInterface_CncChannelList_Channel1_CmdFeedrate 6107
#define DemoId_CncInterface_CncChannelList_Channel1_CmdFeedrate_EURange 6108
#define DemoId_CncInterface_CncChannelList_Channel1_CmdOverride 6109
#define DemoId_CncInterface_CncChannelList_Channel1_CmdOverride_EURange 6110
#define DemoId_CncInterface_CncChannelList_Channel1_DryRunFeed 6111
#define DemoId_CncInterface_CncChannelList_Channel1_DryRunFeed_EURange 6112
#define DemoId_CncInterface_CncChannelList_Channel1_FeedHold 6113
#define DemoId_CncInterface_CncChannelList_Channel1_Id 6114
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpBcsA 6115
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpBcsA_ActPos 6116
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpBcsA_CmdPos 6117
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpBcsA_EngineeringUnits 6118
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpBcsA_EURange 6119
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpBcsA_RemDist 6120
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpBcsB 6121
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpBcsB_ActPos 6122
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpBcsB_CmdPos 6123
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpBcsB_EngineeringUnits 6124
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpBcsB_EURange 6125
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpBcsB_RemDist 6126
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpBcsC 6127
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpBcsC_ActPos 6128
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpBcsC_CmdPos 6129
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpBcsC_EngineeringUnits 6130
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpBcsC_EURange 6131
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpBcsC_RemDist 6132
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpBcsX 6133
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpBcsX_ActPos 6134
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpBcsX_CmdPos 6135
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpBcsX_EngineeringUnits 6136
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpBcsX_EURange 6137
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpBcsX_RemDist 6138
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpBcsY 6139
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpBcsY_ActPos 6140
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpBcsY_CmdPos 6141
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpBcsY_EngineeringUnits 6142
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpBcsY_EURange 6143
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpBcsY_RemDist 6144
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpBcsZ 6145
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpBcsZ_ActPos 6146
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpBcsZ_CmdPos 6147
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpBcsZ_EngineeringUnits 6148
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpBcsZ_EURange 6149
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpBcsZ_RemDist 6150
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpWcsA 6151
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpWcsA_ActPos 6152
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpWcsA_CmdPos 6153
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpWcsA_EngineeringUnits 6154
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpWcsA_EURange 6155
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpWcsA_RemDist 6156
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpWcsB 6157
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpWcsB_ActPos 6158
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpWcsB_CmdPos 6159
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpWcsB_EngineeringUnits 6160
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpWcsB_EURange 6161
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpWcsB_RemDist 6162
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpWcsC 6163
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpWcsC_ActPos 6164
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpWcsC_CmdPos 6165
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpWcsC_EngineeringUnits 6166
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpWcsC_EURange 6167
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpWcsC_RemDist 6168
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpWcsX 6169
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpWcsX_ActPos 6170
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpWcsX_CmdPos 6171
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpWcsX_EngineeringUnits 6172
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpWcsX_EURange 6173
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpWcsX_RemDist 6174
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpWcsY 6175
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpWcsY_ActPos 6176
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpWcsY_CmdPos 6177
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpWcsY_EngineeringUnits 6178
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpWcsY_EURange 6179
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpWcsY_RemDist 6180
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpWcsZ 6181
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpWcsZ_ActPos 6182
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpWcsZ_CmdPos 6183
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpWcsZ_EngineeringUnits 6184
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpWcsZ_EURange 6185
#define DemoId_CncInterface_CncChannelList_Channel1_PosTcpWcsZ_RemDist 6186
#define DemoId_CncInterface_CncChannelList_Channel1_ToolId 6187

/*============================================================================
* Method Identifiers
 *===========================================================================*/


#ifdef _WIN32
#ifdef _UAMODELS_BUILD_DLL
# define UAMODELS_EXPORT __declspec(dllexport)
#elif defined _UAMODELS_USE_DLL
# define UAMODELS_EXPORT __declspec(dllimport)
#else
# define UAMODELS_EXPORT
#endif
#else
# define UAMODELS_EXPORT
#endif

///////////////////////////////////////////////
// Private Class Hiding Macros
#define DEMO_DECLARE_PRIVATE(Class) \
    inline Class##Private* d_func() { return reinterpret_cast<Class##Private *>(d_ptr); } \
    inline const Class##Private* d_func() const { return reinterpret_cast<const Class##Private *>(d_ptr); } \
    friend class Class##Private; \
    Class##Private *d_ptr;

#define DEMO_DECLARE_PUBLIC(Class) \
    inline Class* q_func() { return static_cast<Class *>(q_ptr); } \
    inline const Class* q_func() const { return static_cast<const Class *>(q_ptr); } \
    friend class Class;

#define DEMO_D(Class) Class##Private * const d = d_func()
#define DEMO_CD(Class) const Class##Private * const d = d_func()
#define DEMO_Q(Class) Class * const q = q_func()

#endif // __DEMO_IDENTIFIERS_H__

