/******************************************************************************
** opcuacnc_cncinterfacetype.h
**
**   **************************** auto-generated ****************************
**     This code was generated by a tool: UaModeler
**     Runtime Version: 1.5.0, using C++ OPC UA SDK 1.5.0 template (version 4)
**
**     This is a template file that was generated for your convenience.
**     This file will not be overwritten when generating code again.
**     ADD YOUR IMPLEMTATION HERE!
**   **************************** auto-generated ****************************
**
** Copyright (c) 2006-2016 Unified Automation GmbH. All rights reserved.
**
** Software License Agreement ("SLA") Version 2.5
**
** Unless explicitly acquired and licensed from Licensor under another
** license, the contents of this file are subject to the Software License
** Agreement ("SLA") Version 2.5, or subsequent versions
** as allowed by the SLA, and You may not copy or use this file in either
** source code or executable form, except in compliance with the terms and
** conditions of the SLA.
**
** All software distributed under the SLA is provided strictly on an
** "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED,
** AND LICENSOR HEREBY DISCLAIMS ALL SUCH WARRANTIES, INCLUDING WITHOUT
** LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
** PURPOSE, QUIET ENJOYMENT, OR NON-INFRINGEMENT. See the SLA for specific
** language governing rights and limitations under the SLA.
**
** The complete license agreement can be found here:
** http://unifiedautomation.com/License/SLA/2.5/
**
** Project: C++ OPC Server SDK information model for namespace http://opcfoundation.org/UA/CNC/
**
** Description: OPC Unified Architecture Software Development Kit.
**
** Created: 19.08.2016
**
******************************************************************************/

#ifndef __OPCUACNC_CNCINTERFACETYPE_H__
#define __OPCUACNC_CNCINTERFACETYPE_H__

#include "opcuacnc_cncinterfacetypebase.h"

// Namespace for the UA information model http://opcfoundation.org/UA/CNC/
namespace OpcUaCnc {

/** @brief Class implementing the UaObject interface for the CncInterfaceType.
 *
 * OPC UA Objects are used to represent systems, system components, real-world objects and software
 * objects. They have the NodeClass Object. The detailed description of Objects and their attributes
 * can be found in the general description of the Object node class.
 *
 *  **Object members of the CncInterfaceType:**
 *
 *  Browse Name    | TypeDefinition     | Modelling Rule | See Also
 *  ---------------|--------------------|----------------|-----------------------------------------------------------------
 *  CncAxisList    | CncAxisListType    | Mandatory      | \ref CncInterfaceTypeBase::getCncAxisList "getCncAxisList"
 *  CncChannelList | CncChannelListType | Mandatory      | \ref CncInterfaceTypeBase::getCncChannelList "getCncChannelList"
 *  CncSpindleList | CncSpindleListType | Mandatory      | \ref CncInterfaceTypeBase::getCncSpindleList "getCncSpindleList"
 *
 *  **Variable members of the CncInterfaceType:**
 *
 *  Browse Name    | DataType | TypeDefinition | Modelling Rule | See Also
 *  ---------------|----------|----------------|----------------|-----------------------------------------------------------------------------------------------------------------------------------
 *  Fix            | String   | PropertyType   | Optional       | \ref CncInterfaceTypeBase::getFix "getFix", \ref CncInterfaceTypeBase::setFix "setFix"
 *  Revision       | String   | PropertyType   | Mandatory      | \ref CncInterfaceTypeBase::getRevision "getRevision", \ref CncInterfaceTypeBase::setRevision "setRevision"
 *  VendorName     | String   | PropertyType   | Mandatory      | \ref CncInterfaceTypeBase::getVendorName "getVendorName", \ref CncInterfaceTypeBase::setVendorName "setVendorName"
 *  VendorRevision | String   | PropertyType   | Mandatory      | \ref CncInterfaceTypeBase::getVendorRevision "getVendorRevision", \ref CncInterfaceTypeBase::setVendorRevision "setVendorRevision"
 *  Version        | String   | PropertyType   | Mandatory      | \ref CncInterfaceTypeBase::getVersion "getVersion", \ref CncInterfaceTypeBase::setVersion "setVersion"
 *
 */
class UAMODELS_EXPORT CncInterfaceType:
    public CncInterfaceTypeBase
{
    UA_DISABLE_COPY(CncInterfaceType);
protected:
    // destruction
    virtual ~CncInterfaceType();
public:
    // construction
    CncInterfaceType(const UaNodeId& nodeId, UaObject* pInstanceDeclarationObject, NodeManagerConfig* pNodeConfig, UaMutexRefCounted* pSharedMutex = NULL);
    CncInterfaceType(const UaNodeId& nodeId, const UaString& name, OpcUa_UInt16 browseNameNameSpaceIndex, NodeManagerConfig* pNodeConfig, UaMutexRefCounted* pSharedMutex = NULL);
    CncInterfaceType(
        UaBase::Object*    pBaseNode,
        XmlUaNodeFactoryManager*   pFactory,
        NodeManagerConfig* pNodeConfig,
        UaMutexRefCounted* pSharedMutex = NULL);
    static void createTypes();
    static void clearStaticMembers();


protected:

private:
};

} // End namespace for the UA information model http://opcfoundation.org/UA/CNC/

#endif // #ifndef __OPCUACNCCNCINTERFACETYPE_H__

