/******************************************************************************
** opcuacnc_identifiers.h
**
**   **************************** auto-generated ****************************
**     This code was generated by a tool: UaModeler
**     Runtime Version: 1.5.0, using C++ OPC UA SDK 1.5.0 template (version 4)
**
**     Changes to this file may cause incorrect behavior and will be lost if
**     the code is regenerated.
**   **************************** auto-generated ****************************
**
** Copyright (c) 2006-2016 Unified Automation GmbH. All rights reserved.
**
** Software License Agreement ("SLA") Version 2.5
**
** Unless explicitly acquired and licensed from Licensor under another
** license, the contents of this file are subject to the Software License
** Agreement ("SLA") Version 2.5, or subsequent versions
** as allowed by the SLA, and You may not copy or use this file in either
** source code or executable form, except in compliance with the terms and
** conditions of the SLA.
**
** All software distributed under the SLA is provided strictly on an
** "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED,
** AND LICENSOR HEREBY DISCLAIMS ALL SUCH WARRANTIES, INCLUDING WITHOUT
** LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
** PURPOSE, QUIET ENJOYMENT, OR NON-INFRINGEMENT. See the SLA for specific
** language governing rights and limitations under the SLA.
**
** The complete license agreement can be found here:
** http://unifiedautomation.com/License/SLA/2.5/
**
** Project: C++ OPC Server SDK information model for namespace http://opcfoundation.org/UA/CNC/
**
** Description: OPC Unified Architecture Software Development Kit.
**
** Created: 19.08.2016
**
******************************************************************************/

#ifndef __OPCUACNC_IDENTIFIERS_H__
#define __OPCUACNC_IDENTIFIERS_H__

#define OpcUaCnc_NameSpaceUri "http://opcfoundation.org/UA/CNC/"

#include "version_coremodule.h"
#if (PROD_MAJOR != 1 || (PROD_MAJOR == 1 && PROD_MINOR < 5) || (PROD_MAJOR == 1 && PROD_MINOR == 5 && PROD_MINOR2 < 0))
#if ! (PROD_MAJOR == 1 && PROD_MINOR == 3 && PROD_MINOR2 == 0 && CPP_SDK_BUILD == 193)
#error The code is generated for SDK version 1.5.0
#endif
#endif

/*============================================================================
* ObjectType Identifiers
 *===========================================================================*/
#define OpcUaCncId_CncAlarmType 1010
#define OpcUaCncId_CncMessageType 1011
#define OpcUaCncId_CncAxisListType 1002
#define OpcUaCncId_CncChannelListType 1004
#define OpcUaCncId_CncComponentType 1005
#define OpcUaCncId_CncChannelType 1006
#define OpcUaCncId_CncDriveType 1007
#define OpcUaCncId_CncAxisType 1008
#define OpcUaCncId_CncSpindleType 1009
#define OpcUaCncId_CncInterfaceType 1001
#define OpcUaCncId_CncSpindleListType 1003

/*============================================================================
* VariableType Identifiers
 *===========================================================================*/
#define OpcUaCncId_CncPositionVariableType 2001

/*============================================================================
* DataType Identifiers
 *===========================================================================*/
#define OpcUaCncId_CncAxisStatus 3001
#define OpcUaCncId_CncAxisStatus_EnumStrings 6001
#define OpcUaCncId_CncChannelProgramStatus 3005
#define OpcUaCncId_CncChannelProgramStatus_EnumStrings 6005
#define OpcUaCncId_CncChannelStatus 3004
#define OpcUaCncId_CncChannelStatus_EnumStrings 6004
#define OpcUaCncId_CncOperationMode 3006
#define OpcUaCncId_CncOperationMode_EnumStrings 6006
#define OpcUaCncId_CncSpindleStatus 3002
#define OpcUaCncId_CncSpindleStatus_EnumStrings 6002
#define OpcUaCncId_CncSpindleTurnDirection 3003
#define OpcUaCncId_CncSpindleTurnDirection_EnumStrings 6003
#define OpcUaCncId_CncPositionType 3007
#define OpcUaCncId_CncPositionType_Encoding_DefaultBinary 5002
#define OpcUaCncId_CncPositionType_Encoding_DefaultXml 5003
#define OpcUaCncId_BinarySchema 6665
#define OpcUaCncId_BinarySchema_CncPositionType 6666
#define OpcUaCncId_BinarySchema_NamespaceUri 6667
#define OpcUaCncId_XmlSchema 6668
#define OpcUaCncId_XmlSchema_CncPositionType 6669
#define OpcUaCncId_XmlSchema_NamespaceUri 6670

/*============================================================================
* ReferenceType Identifiers
 *===========================================================================*/

/*============================================================================
* Object Identifiers
 *===========================================================================*/
#define OpcUaCncId_CncAxisListType_CncAxis 5008
#define OpcUaCncId_CncChannelListType_CncChannel 5010
#define OpcUaCncId_CncChannelType_CncAxis 5011
#define OpcUaCncId_CncChannelType_CncSpindle 5012
#define OpcUaCncId_CncInterfaceType_CncAxisList 5004
#define OpcUaCncId_CncInterfaceType_CncChannelList 5006
#define OpcUaCncId_CncInterfaceType_CncSpindleList 5005
#define OpcUaCncId_CncSpindleListType_CncSpindle 5009
#define OpcUaCncId_CncInterface 5007
#define OpcUaCncId_CncInterface_CncAxisList 5001
#define OpcUaCncId_CncInterface_CncChannelList 5013
#define OpcUaCncId_CncInterface_CncSpindleList 5014

/*============================================================================
* Variable Identifiers
 *===========================================================================*/
#define OpcUaCncId_CncAlarmType_AlarmIdentifier 6087
#define OpcUaCncId_CncAlarmType_AuxParameters 6088
#define OpcUaCncId_CncAlarmType_HelpSource 6089
#define OpcUaCncId_CncAxisListType_CncAxis_ActChannel 6303
#define OpcUaCncId_CncAxisListType_CncAxis_ActLoad 6304
#define OpcUaCncId_CncAxisListType_CncAxis_ActLoad_EURange 6305
#define OpcUaCncId_CncAxisListType_CncAxis_ActPower 6306
#define OpcUaCncId_CncAxisListType_CncAxis_ActPower_EURange 6307
#define OpcUaCncId_CncAxisListType_CncAxis_ActStatus 6296
#define OpcUaCncId_CncAxisListType_CncAxis_ActTorque 6308
#define OpcUaCncId_CncAxisListType_CncAxis_ActTorque_EURange 6309
#define OpcUaCncId_CncAxisListType_CncAxis_CmdTorque 6310
#define OpcUaCncId_CncAxisListType_CncAxis_CmdTorque_EURange 6311
#define OpcUaCncId_CncAxisListType_CncAxis_IsInactive 6312
#define OpcUaCncId_CncAxisListType_CncAxis_IsReferenced 6297
#define OpcUaCncId_CncAxisListType_CncAxis_IsRotational 6298
#define OpcUaCncId_CncAxisListType_CncAxis_IsVirtual 6313
#define OpcUaCncId_CncAxisListType_CncAxis_PosDirect 6299
#define OpcUaCncId_CncAxisListType_CncAxis_PosDirect_ActPos 6344
#define OpcUaCncId_CncAxisListType_CncAxis_PosDirect_CmdPos 6345
#define OpcUaCncId_CncAxisListType_CncAxis_PosDirect_EngineeringUnits 6346
#define OpcUaCncId_CncAxisListType_CncAxis_PosDirect_EURange 6347
#define OpcUaCncId_CncAxisListType_CncAxis_PosDirect_RemDist 6348
#define OpcUaCncId_CncAxisListType_CncAxis_PosIndirect 6300
#define OpcUaCncId_CncAxisListType_CncAxis_PosIndirect_ActPos 6359
#define OpcUaCncId_CncAxisListType_CncAxis_PosIndirect_CmdPos 6360
#define OpcUaCncId_CncAxisListType_CncAxis_PosIndirect_EngineeringUnits 6361
#define OpcUaCncId_CncAxisListType_CncAxis_PosIndirect_EURange 6362
#define OpcUaCncId_CncAxisListType_CncAxis_PosIndirect_RemDist 6363
#define OpcUaCncId_CncAxisListType_CncAxis_ZeroOffset 6301
#define OpcUaCncId_CncAxisListType_CncAxis_ZeroOffset_EURange 6302
#define OpcUaCncId_CncChannelListType_CncChannel_ActFeedrate 6108
#define OpcUaCncId_CncChannelListType_CncChannel_ActFeedrate_EURange 6109
#define OpcUaCncId_CncChannelListType_CncChannel_ActGFunctions 6110
#define OpcUaCncId_CncChannelListType_CncChannel_ActJogIncrement 6111
#define OpcUaCncId_CncChannelListType_CncChannel_ActJogIncrement_EURange 6112
#define OpcUaCncId_CncChannelListType_CncChannel_ActMainProgramFile 6113
#define OpcUaCncId_CncChannelListType_CncChannel_ActMainProgramFileOffset 6114
#define OpcUaCncId_CncChannelListType_CncChannel_ActMainProgramLine 6115
#define OpcUaCncId_CncChannelListType_CncChannel_ActMainProgramName 6116
#define OpcUaCncId_CncChannelListType_CncChannel_ActMFunctions 6117
#define OpcUaCncId_CncChannelListType_CncChannel_ActModalOffsetFunction 6118
#define OpcUaCncId_CncChannelListType_CncChannel_ActOperationMode 6119
#define OpcUaCncId_CncChannelListType_CncChannel_ActOverride 6120
#define OpcUaCncId_CncChannelListType_CncChannel_ActOverride_EURange 6121
#define OpcUaCncId_CncChannelListType_CncChannel_ActProgramBlock 6122
#define OpcUaCncId_CncChannelListType_CncChannel_ActProgramFile 6123
#define OpcUaCncId_CncChannelListType_CncChannel_ActProgramFileOffset 6124
#define OpcUaCncId_CncChannelListType_CncChannel_ActProgramLine 6125
#define OpcUaCncId_CncChannelListType_CncChannel_ActProgramName 6126
#define OpcUaCncId_CncChannelListType_CncChannel_ActProgramStatus 6127
#define OpcUaCncId_CncChannelListType_CncChannel_ActStatus 6128
#define OpcUaCncId_CncChannelListType_CncChannel_BlockMode 6129
#define OpcUaCncId_CncChannelListType_CncChannel_CmdFeedrate 6130
#define OpcUaCncId_CncChannelListType_CncChannel_CmdFeedrate_EURange 6131
#define OpcUaCncId_CncChannelListType_CncChannel_CmdOverride 6132
#define OpcUaCncId_CncChannelListType_CncChannel_CmdOverride_EURange 6133
#define OpcUaCncId_CncChannelListType_CncChannel_DryRunFeed 6134
#define OpcUaCncId_CncChannelListType_CncChannel_DryRunFeed_EURange 6135
#define OpcUaCncId_CncChannelListType_CncChannel_FeedHold 6136
#define OpcUaCncId_CncChannelListType_CncChannel_Id 6137
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpBcsA 6138
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpBcsA_ActPos 6181
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpBcsA_CmdPos 6182
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpBcsA_EngineeringUnits 6183
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpBcsA_EURange 6184
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpBcsA_RemDist 6185
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpBcsB 6139
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpBcsB_ActPos 6191
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpBcsB_CmdPos 6192
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpBcsB_EngineeringUnits 6193
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpBcsB_EURange 6194
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpBcsB_RemDist 6195
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpBcsC 6140
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpBcsC_ActPos 6201
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpBcsC_CmdPos 6202
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpBcsC_EngineeringUnits 6203
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpBcsC_EURange 6204
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpBcsC_RemDist 6205
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpBcsX 6141
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpBcsX_ActPos 6211
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpBcsX_CmdPos 6212
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpBcsX_EngineeringUnits 6213
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpBcsX_EURange 6214
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpBcsX_RemDist 6215
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpBcsY 6142
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpBcsY_ActPos 6221
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpBcsY_CmdPos 6222
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpBcsY_EngineeringUnits 6223
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpBcsY_EURange 6224
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpBcsY_RemDist 6225
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpBcsZ 6143
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpBcsZ_ActPos 6231
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpBcsZ_CmdPos 6232
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpBcsZ_EngineeringUnits 6233
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpBcsZ_EURange 6234
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpBcsZ_RemDist 6235
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpWcsA 6144
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpWcsA_ActPos 6241
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpWcsA_CmdPos 6242
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpWcsA_EngineeringUnits 6243
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpWcsA_EURange 6244
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpWcsA_RemDist 6245
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpWcsB 6145
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpWcsB_ActPos 6251
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpWcsB_CmdPos 6252
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpWcsB_EngineeringUnits 6253
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpWcsB_EURange 6254
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpWcsB_RemDist 6255
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpWcsC 6146
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpWcsC_ActPos 6261
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpWcsC_CmdPos 6262
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpWcsC_EngineeringUnits 6263
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpWcsC_EURange 6264
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpWcsC_RemDist 6265
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpWcsX 6147
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpWcsX_ActPos 6271
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpWcsX_CmdPos 6272
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpWcsX_EngineeringUnits 6273
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpWcsX_EURange 6274
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpWcsX_RemDist 6275
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpWcsY 6148
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpWcsY_ActPos 6281
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpWcsY_CmdPos 6282
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpWcsY_EngineeringUnits 6283
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpWcsY_EURange 6284
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpWcsY_RemDist 6285
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpWcsZ 6149
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpWcsZ_ActPos 6291
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpWcsZ_CmdPos 6292
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpWcsZ_EngineeringUnits 6293
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpWcsZ_EURange 6294
#define OpcUaCncId_CncChannelListType_CncChannel_PosTcpWcsZ_RemDist 6295
#define OpcUaCncId_CncChannelListType_CncChannel_ToolId 6150
#define OpcUaCncId_CncChannelType_CncAxis_ActChannel 6097
#define OpcUaCncId_CncChannelType_CncAxis_ActLoad 6098
#define OpcUaCncId_CncChannelType_CncAxis_ActLoad_EURange 6099
#define OpcUaCncId_CncChannelType_CncAxis_ActPower 6100
#define OpcUaCncId_CncChannelType_CncAxis_ActPower_EURange 6101
#define OpcUaCncId_CncChannelType_CncAxis_ActStatus 6090
#define OpcUaCncId_CncChannelType_CncAxis_ActTorque 6102
#define OpcUaCncId_CncChannelType_CncAxis_ActTorque_EURange 6103
#define OpcUaCncId_CncChannelType_CncAxis_CmdTorque 6104
#define OpcUaCncId_CncChannelType_CncAxis_CmdTorque_EURange 6105
#define OpcUaCncId_CncChannelType_CncAxis_IsInactive 6106
#define OpcUaCncId_CncChannelType_CncAxis_IsReferenced 6091
#define OpcUaCncId_CncChannelType_CncAxis_IsRotational 6092
#define OpcUaCncId_CncChannelType_CncAxis_IsVirtual 6107
#define OpcUaCncId_CncChannelType_CncAxis_PosDirect 6093
#define OpcUaCncId_CncChannelType_CncAxis_PosDirect_ActPos 6349
#define OpcUaCncId_CncChannelType_CncAxis_PosDirect_CmdPos 6350
#define OpcUaCncId_CncChannelType_CncAxis_PosDirect_EngineeringUnits 6351
#define OpcUaCncId_CncChannelType_CncAxis_PosDirect_EURange 6352
#define OpcUaCncId_CncChannelType_CncAxis_PosDirect_RemDist 6353
#define OpcUaCncId_CncChannelType_CncAxis_PosIndirect 6094
#define OpcUaCncId_CncChannelType_CncAxis_PosIndirect_ActPos 6364
#define OpcUaCncId_CncChannelType_CncAxis_PosIndirect_CmdPos 6365
#define OpcUaCncId_CncChannelType_CncAxis_PosIndirect_EngineeringUnits 6366
#define OpcUaCncId_CncChannelType_CncAxis_PosIndirect_EURange 6367
#define OpcUaCncId_CncChannelType_CncAxis_PosIndirect_RemDist 6368
#define OpcUaCncId_CncChannelType_CncAxis_ZeroOffset 6095
#define OpcUaCncId_CncChannelType_CncAxis_ZeroOffset_EURange 6096
#define OpcUaCncId_CncChannelType_CncSpindle_ActChannel 6165
#define OpcUaCncId_CncChannelType_CncSpindle_ActChuckPowerStatus 6151
#define OpcUaCncId_CncChannelType_CncSpindle_ActGear 6152
#define OpcUaCncId_CncChannelType_CncSpindle_ActLoad 6166
#define OpcUaCncId_CncChannelType_CncSpindle_ActLoad_EURange 6167
#define OpcUaCncId_CncChannelType_CncSpindle_ActOverride 6153
#define OpcUaCncId_CncChannelType_CncSpindle_ActOverride_EURange 6154
#define OpcUaCncId_CncChannelType_CncSpindle_ActPower 6168
#define OpcUaCncId_CncChannelType_CncSpindle_ActPower_EURange 6169
#define OpcUaCncId_CncChannelType_CncSpindle_ActSpeed 6155
#define OpcUaCncId_CncChannelType_CncSpindle_ActSpeed_EURange 6156
#define OpcUaCncId_CncChannelType_CncSpindle_ActStatus 6157
#define OpcUaCncId_CncChannelType_CncSpindle_ActTorque 6170
#define OpcUaCncId_CncChannelType_CncSpindle_ActTorque_EURange 6171
#define OpcUaCncId_CncChannelType_CncSpindle_ActTurnDirection 6158
#define OpcUaCncId_CncChannelType_CncSpindle_AnglePos 6159
#define OpcUaCncId_CncChannelType_CncSpindle_AnglePos_ActPos 6379
#define OpcUaCncId_CncChannelType_CncSpindle_AnglePos_CmdPos 6380
#define OpcUaCncId_CncChannelType_CncSpindle_AnglePos_EngineeringUnits 6381
#define OpcUaCncId_CncChannelType_CncSpindle_AnglePos_EURange 6382
#define OpcUaCncId_CncChannelType_CncSpindle_AnglePos_RemDist 6383
#define OpcUaCncId_CncChannelType_CncSpindle_CmdGear 6160
#define OpcUaCncId_CncChannelType_CncSpindle_CmdOverride 6161
#define OpcUaCncId_CncChannelType_CncSpindle_CmdOverride_EURange 6162
#define OpcUaCncId_CncChannelType_CncSpindle_CmdSpeed 6163
#define OpcUaCncId_CncChannelType_CncSpindle_CmdSpeed_EURange 6164
#define OpcUaCncId_CncChannelType_CncSpindle_CmdTorque 6172
#define OpcUaCncId_CncChannelType_CncSpindle_CmdTorque_EURange 6173
#define OpcUaCncId_CncChannelType_CncSpindle_IsInactive 6174
#define OpcUaCncId_CncChannelType_CncSpindle_IsVirtual 6175
#define OpcUaCncId_CncChannelType_ActFeedrate 6012
#define OpcUaCncId_CncChannelType_ActFeedrate_EURange 6013
#define OpcUaCncId_CncChannelType_ActGFunctions 6014
#define OpcUaCncId_CncChannelType_ActJogIncrement 6015
#define OpcUaCncId_CncChannelType_ActJogIncrement_EURange 6016
#define OpcUaCncId_CncChannelType_ActMainProgramFile 6017
#define OpcUaCncId_CncChannelType_ActMainProgramFileOffset 6018
#define OpcUaCncId_CncChannelType_ActMainProgramLine 6019
#define OpcUaCncId_CncChannelType_ActMainProgramName 6020
#define OpcUaCncId_CncChannelType_ActMFunctions 6021
#define OpcUaCncId_CncChannelType_ActModalOffsetFunction 6022
#define OpcUaCncId_CncChannelType_ActOperationMode 6023
#define OpcUaCncId_CncChannelType_ActOverride 6024
#define OpcUaCncId_CncChannelType_ActOverride_EURange 6025
#define OpcUaCncId_CncChannelType_ActProgramBlock 6026
#define OpcUaCncId_CncChannelType_ActProgramFile 6027
#define OpcUaCncId_CncChannelType_ActProgramFileOffset 6028
#define OpcUaCncId_CncChannelType_ActProgramLine 6029
#define OpcUaCncId_CncChannelType_ActProgramName 6030
#define OpcUaCncId_CncChannelType_ActProgramStatus 6031
#define OpcUaCncId_CncChannelType_ActStatus 6032
#define OpcUaCncId_CncChannelType_BlockMode 6033
#define OpcUaCncId_CncChannelType_CmdFeedrate 6034
#define OpcUaCncId_CncChannelType_CmdFeedrate_EURange 6035
#define OpcUaCncId_CncChannelType_CmdOverride 6036
#define OpcUaCncId_CncChannelType_CmdOverride_EURange 6037
#define OpcUaCncId_CncChannelType_DryRunFeed 6038
#define OpcUaCncId_CncChannelType_DryRunFeed_EURange 6039
#define OpcUaCncId_CncChannelType_FeedHold 6040
#define OpcUaCncId_CncChannelType_Id 6041
#define OpcUaCncId_CncChannelType_PosTcpBcsA 6042
#define OpcUaCncId_CncChannelType_PosTcpBcsA_ActPos 6176
#define OpcUaCncId_CncChannelType_PosTcpBcsA_CmdPos 6177
#define OpcUaCncId_CncChannelType_PosTcpBcsA_EngineeringUnits 6178
#define OpcUaCncId_CncChannelType_PosTcpBcsA_EURange 6179
#define OpcUaCncId_CncChannelType_PosTcpBcsA_RemDist 6180
#define OpcUaCncId_CncChannelType_PosTcpBcsB 6043
#define OpcUaCncId_CncChannelType_PosTcpBcsB_ActPos 6186
#define OpcUaCncId_CncChannelType_PosTcpBcsB_CmdPos 6187
#define OpcUaCncId_CncChannelType_PosTcpBcsB_EngineeringUnits 6188
#define OpcUaCncId_CncChannelType_PosTcpBcsB_EURange 6189
#define OpcUaCncId_CncChannelType_PosTcpBcsB_RemDist 6190
#define OpcUaCncId_CncChannelType_PosTcpBcsC 6044
#define OpcUaCncId_CncChannelType_PosTcpBcsC_ActPos 6196
#define OpcUaCncId_CncChannelType_PosTcpBcsC_CmdPos 6197
#define OpcUaCncId_CncChannelType_PosTcpBcsC_EngineeringUnits 6198
#define OpcUaCncId_CncChannelType_PosTcpBcsC_EURange 6199
#define OpcUaCncId_CncChannelType_PosTcpBcsC_RemDist 6200
#define OpcUaCncId_CncChannelType_PosTcpBcsX 6045
#define OpcUaCncId_CncChannelType_PosTcpBcsX_ActPos 6206
#define OpcUaCncId_CncChannelType_PosTcpBcsX_CmdPos 6207
#define OpcUaCncId_CncChannelType_PosTcpBcsX_EngineeringUnits 6208
#define OpcUaCncId_CncChannelType_PosTcpBcsX_EURange 6209
#define OpcUaCncId_CncChannelType_PosTcpBcsX_RemDist 6210
#define OpcUaCncId_CncChannelType_PosTcpBcsY 6046
#define OpcUaCncId_CncChannelType_PosTcpBcsY_ActPos 6216
#define OpcUaCncId_CncChannelType_PosTcpBcsY_CmdPos 6217
#define OpcUaCncId_CncChannelType_PosTcpBcsY_EngineeringUnits 6218
#define OpcUaCncId_CncChannelType_PosTcpBcsY_EURange 6219
#define OpcUaCncId_CncChannelType_PosTcpBcsY_RemDist 6220
#define OpcUaCncId_CncChannelType_PosTcpBcsZ 6047
#define OpcUaCncId_CncChannelType_PosTcpBcsZ_ActPos 6226
#define OpcUaCncId_CncChannelType_PosTcpBcsZ_CmdPos 6227
#define OpcUaCncId_CncChannelType_PosTcpBcsZ_EngineeringUnits 6228
#define OpcUaCncId_CncChannelType_PosTcpBcsZ_EURange 6229
#define OpcUaCncId_CncChannelType_PosTcpBcsZ_RemDist 6230
#define OpcUaCncId_CncChannelType_PosTcpWcsA 6048
#define OpcUaCncId_CncChannelType_PosTcpWcsA_ActPos 6236
#define OpcUaCncId_CncChannelType_PosTcpWcsA_CmdPos 6237
#define OpcUaCncId_CncChannelType_PosTcpWcsA_EngineeringUnits 6238
#define OpcUaCncId_CncChannelType_PosTcpWcsA_EURange 6239
#define OpcUaCncId_CncChannelType_PosTcpWcsA_RemDist 6240
#define OpcUaCncId_CncChannelType_PosTcpWcsB 6049
#define OpcUaCncId_CncChannelType_PosTcpWcsB_ActPos 6246
#define OpcUaCncId_CncChannelType_PosTcpWcsB_CmdPos 6247
#define OpcUaCncId_CncChannelType_PosTcpWcsB_EngineeringUnits 6248
#define OpcUaCncId_CncChannelType_PosTcpWcsB_EURange 6249
#define OpcUaCncId_CncChannelType_PosTcpWcsB_RemDist 6250
#define OpcUaCncId_CncChannelType_PosTcpWcsC 6050
#define OpcUaCncId_CncChannelType_PosTcpWcsC_ActPos 6256
#define OpcUaCncId_CncChannelType_PosTcpWcsC_CmdPos 6257
#define OpcUaCncId_CncChannelType_PosTcpWcsC_EngineeringUnits 6258
#define OpcUaCncId_CncChannelType_PosTcpWcsC_EURange 6259
#define OpcUaCncId_CncChannelType_PosTcpWcsC_RemDist 6260
#define OpcUaCncId_CncChannelType_PosTcpWcsX 6051
#define OpcUaCncId_CncChannelType_PosTcpWcsX_ActPos 6266
#define OpcUaCncId_CncChannelType_PosTcpWcsX_CmdPos 6267
#define OpcUaCncId_CncChannelType_PosTcpWcsX_EngineeringUnits 6268
#define OpcUaCncId_CncChannelType_PosTcpWcsX_EURange 6269
#define OpcUaCncId_CncChannelType_PosTcpWcsX_RemDist 6270
#define OpcUaCncId_CncChannelType_PosTcpWcsY 6052
#define OpcUaCncId_CncChannelType_PosTcpWcsY_ActPos 6276
#define OpcUaCncId_CncChannelType_PosTcpWcsY_CmdPos 6277
#define OpcUaCncId_CncChannelType_PosTcpWcsY_EngineeringUnits 6278
#define OpcUaCncId_CncChannelType_PosTcpWcsY_EURange 6279
#define OpcUaCncId_CncChannelType_PosTcpWcsY_RemDist 6280
#define OpcUaCncId_CncChannelType_PosTcpWcsZ 6053
#define OpcUaCncId_CncChannelType_PosTcpWcsZ_ActPos 6286
#define OpcUaCncId_CncChannelType_PosTcpWcsZ_CmdPos 6287
#define OpcUaCncId_CncChannelType_PosTcpWcsZ_EngineeringUnits 6288
#define OpcUaCncId_CncChannelType_PosTcpWcsZ_EURange 6289
#define OpcUaCncId_CncChannelType_PosTcpWcsZ_RemDist 6290
#define OpcUaCncId_CncChannelType_ToolId 6054
#define OpcUaCncId_CncDriveType_ActChannel 6055
#define OpcUaCncId_CncDriveType_ActLoad 6056
#define OpcUaCncId_CncDriveType_ActLoad_EURange 6057
#define OpcUaCncId_CncDriveType_ActPower 6058
#define OpcUaCncId_CncDriveType_ActPower_EURange 6059
#define OpcUaCncId_CncDriveType_ActTorque 6060
#define OpcUaCncId_CncDriveType_ActTorque_EURange 6061
#define OpcUaCncId_CncDriveType_CmdTorque 6062
#define OpcUaCncId_CncDriveType_CmdTorque_EURange 6063
#define OpcUaCncId_CncDriveType_IsInactive 6064
#define OpcUaCncId_CncDriveType_IsVirtual 6065
#define OpcUaCncId_CncAxisType_ActStatus 6066
#define OpcUaCncId_CncAxisType_IsReferenced 6067
#define OpcUaCncId_CncAxisType_IsRotational 6068
#define OpcUaCncId_CncAxisType_PosDirect 6069
#define OpcUaCncId_CncAxisType_PosDirect_ActPos 6339
#define OpcUaCncId_CncAxisType_PosDirect_CmdPos 6340
#define OpcUaCncId_CncAxisType_PosDirect_EngineeringUnits 6341
#define OpcUaCncId_CncAxisType_PosDirect_EURange 6342
#define OpcUaCncId_CncAxisType_PosDirect_RemDist 6343
#define OpcUaCncId_CncAxisType_PosIndirect 6070
#define OpcUaCncId_CncAxisType_PosIndirect_ActPos 6354
#define OpcUaCncId_CncAxisType_PosIndirect_CmdPos 6355
#define OpcUaCncId_CncAxisType_PosIndirect_EngineeringUnits 6356
#define OpcUaCncId_CncAxisType_PosIndirect_EURange 6357
#define OpcUaCncId_CncAxisType_PosIndirect_RemDist 6358
#define OpcUaCncId_CncAxisType_ZeroOffset 6071
#define OpcUaCncId_CncAxisType_ZeroOffset_EURange 6072
#define OpcUaCncId_CncSpindleType_ActChuckPowerStatus 6073
#define OpcUaCncId_CncSpindleType_ActGear 6074
#define OpcUaCncId_CncSpindleType_ActOverride 6075
#define OpcUaCncId_CncSpindleType_ActOverride_EURange 6076
#define OpcUaCncId_CncSpindleType_ActSpeed 6077
#define OpcUaCncId_CncSpindleType_ActSpeed_EURange 6078
#define OpcUaCncId_CncSpindleType_ActStatus 6079
#define OpcUaCncId_CncSpindleType_ActTurnDirection 6080
#define OpcUaCncId_CncSpindleType_AnglePos 6081
#define OpcUaCncId_CncSpindleType_AnglePos_ActPos 6369
#define OpcUaCncId_CncSpindleType_AnglePos_CmdPos 6370
#define OpcUaCncId_CncSpindleType_AnglePos_EngineeringUnits 6371
#define OpcUaCncId_CncSpindleType_AnglePos_EURange 6372
#define OpcUaCncId_CncSpindleType_AnglePos_RemDist 6373
#define OpcUaCncId_CncSpindleType_CmdGear 6082
#define OpcUaCncId_CncSpindleType_CmdOverride 6083
#define OpcUaCncId_CncSpindleType_CmdOverride_EURange 6084
#define OpcUaCncId_CncSpindleType_CmdSpeed 6085
#define OpcUaCncId_CncSpindleType_CmdSpeed_EURange 6086
#define OpcUaCncId_CncInterfaceType_Fix 6007
#define OpcUaCncId_CncInterfaceType_Revision 6008
#define OpcUaCncId_CncInterfaceType_VendorName 6009
#define OpcUaCncId_CncInterfaceType_VendorRevision 6010
#define OpcUaCncId_CncInterfaceType_Version 6011
#define OpcUaCncId_CncSpindleListType_CncSpindle_ActChannel 6328
#define OpcUaCncId_CncSpindleListType_CncSpindle_ActChuckPowerStatus 6314
#define OpcUaCncId_CncSpindleListType_CncSpindle_ActGear 6315
#define OpcUaCncId_CncSpindleListType_CncSpindle_ActLoad 6329
#define OpcUaCncId_CncSpindleListType_CncSpindle_ActLoad_EURange 6330
#define OpcUaCncId_CncSpindleListType_CncSpindle_ActOverride 6316
#define OpcUaCncId_CncSpindleListType_CncSpindle_ActOverride_EURange 6317
#define OpcUaCncId_CncSpindleListType_CncSpindle_ActPower 6331
#define OpcUaCncId_CncSpindleListType_CncSpindle_ActPower_EURange 6332
#define OpcUaCncId_CncSpindleListType_CncSpindle_ActSpeed 6318
#define OpcUaCncId_CncSpindleListType_CncSpindle_ActSpeed_EURange 6319
#define OpcUaCncId_CncSpindleListType_CncSpindle_ActStatus 6320
#define OpcUaCncId_CncSpindleListType_CncSpindle_ActTorque 6333
#define OpcUaCncId_CncSpindleListType_CncSpindle_ActTorque_EURange 6334
#define OpcUaCncId_CncSpindleListType_CncSpindle_ActTurnDirection 6321
#define OpcUaCncId_CncSpindleListType_CncSpindle_AnglePos 6322
#define OpcUaCncId_CncSpindleListType_CncSpindle_AnglePos_ActPos 6374
#define OpcUaCncId_CncSpindleListType_CncSpindle_AnglePos_CmdPos 6375
#define OpcUaCncId_CncSpindleListType_CncSpindle_AnglePos_EngineeringUnits 6376
#define OpcUaCncId_CncSpindleListType_CncSpindle_AnglePos_EURange 6377
#define OpcUaCncId_CncSpindleListType_CncSpindle_AnglePos_RemDist 6378
#define OpcUaCncId_CncSpindleListType_CncSpindle_CmdGear 6323
#define OpcUaCncId_CncSpindleListType_CncSpindle_CmdOverride 6324
#define OpcUaCncId_CncSpindleListType_CncSpindle_CmdOverride_EURange 6325
#define OpcUaCncId_CncSpindleListType_CncSpindle_CmdSpeed 6326
#define OpcUaCncId_CncSpindleListType_CncSpindle_CmdSpeed_EURange 6327
#define OpcUaCncId_CncSpindleListType_CncSpindle_CmdTorque 6335
#define OpcUaCncId_CncSpindleListType_CncSpindle_CmdTorque_EURange 6336
#define OpcUaCncId_CncSpindleListType_CncSpindle_IsInactive 6337
#define OpcUaCncId_CncSpindleListType_CncSpindle_IsVirtual 6338
#define OpcUaCncId_CncPositionVariableType_ActPos 6500
#define OpcUaCncId_CncPositionVariableType_CmdPos 6501
#define OpcUaCncId_CncPositionVariableType_EngineeringUnits 6502
#define OpcUaCncId_CncPositionVariableType_EURange 6503
#define OpcUaCncId_CncPositionVariableType_RemDist 6504
#define OpcUaCncId_CncInterface_Revision 6384
#define OpcUaCncId_CncInterface_VendorName 6385
#define OpcUaCncId_CncInterface_VendorRevision 6386
#define OpcUaCncId_CncInterface_Version 6387

/*============================================================================
* Method Identifiers
 *===========================================================================*/


#ifdef _WIN32
#ifdef _UAMODELS_BUILD_DLL
# define UAMODELS_EXPORT __declspec(dllexport)
#elif defined _UAMODELS_USE_DLL
# define UAMODELS_EXPORT __declspec(dllimport)
#else
# define UAMODELS_EXPORT
#endif
#else
# define UAMODELS_EXPORT
#endif

///////////////////////////////////////////////
// Private Class Hiding Macros
#define OPCUACNC_DECLARE_PRIVATE(Class) \
    inline Class##Private* d_func() { return reinterpret_cast<Class##Private *>(d_ptr); } \
    inline const Class##Private* d_func() const { return reinterpret_cast<const Class##Private *>(d_ptr); } \
    friend class Class##Private; \
    Class##Private *d_ptr;

#define OPCUACNC_DECLARE_PUBLIC(Class) \
    inline Class* q_func() { return static_cast<Class *>(q_ptr); } \
    inline const Class* q_func() const { return static_cast<const Class *>(q_ptr); } \
    friend class Class;

#define OPCUACNC_D(Class) Class##Private * const d = d_func()
#define OPCUACNC_CD(Class) const Class##Private * const d = d_func()
#define OPCUACNC_Q(Class) Class * const q = q_func()

#endif // __OPCUACNC_IDENTIFIERS_H__

