/******************************************************************************
** opcuacnc_cncpositiontype.cpp
**
**   **************************** auto-generated ****************************
**     This code was generated by a tool: UaModeler
**     Runtime Version: 1.5.0, using C++ OPC UA SDK 1.5.0 template (version 4)
**
**     Changes to this file may cause incorrect behavior and will be lost if
**     the code is regenerated.
**   **************************** auto-generated ****************************
**
** Copyright (c) 2006-2016 Unified Automation GmbH. All rights reserved.
**
** Software License Agreement ("SLA") Version 2.5
**
** Unless explicitly acquired and licensed from Licensor under another
** license, the contents of this file are subject to the Software License
** Agreement ("SLA") Version 2.5, or subsequent versions
** as allowed by the SLA, and You may not copy or use this file in either
** source code or executable form, except in compliance with the terms and
** conditions of the SLA.
**
** All software distributed under the SLA is provided strictly on an
** "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED,
** AND LICENSOR HEREBY DISCLAIMS ALL SUCH WARRANTIES, INCLUDING WITHOUT
** LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
** PURPOSE, QUIET ENJOYMENT, OR NON-INFRINGEMENT. See the SLA for specific
** language governing rights and limitations under the SLA.
**
** The complete license agreement can be found here:
** http://unifiedautomation.com/License/SLA/2.5/
**
** Project: C++ OPC Server SDK information model for namespace http://opcfoundation.org/UA/CNC/
**
** Description: OPC Unified Architecture Software Development Kit.
**
** Created: 19.08.2016
**
******************************************************************************/

#include "opcuacnc_cncpositiontype.h"

#include <opcua_datetime.h>

#include "uavariant.h"
#include "uadatavalue.h"
#include "uaextensionobject.h"
#include "uaatomic.h"

// Namespace for the UA information model http://opcfoundation.org/UA/CNC/
namespace OpcUaCnc {

/******************************************************************************
** Class CncPositionTypePrivate
******************************************************************************/
class CncPositionTypePrivate : private OpcUaCnc_CncPositionType
{
    CncPositionTypePrivate(const CncPositionTypePrivate &other);
public:
    CncPositionTypePrivate();
    explicit CncPositionTypePrivate(bool bStatic);
    explicit CncPositionTypePrivate(const OpcUaCnc_CncPositionType &other);
    ~CncPositionTypePrivate();

    int addRef();
    int release();
    inline int refCount() { return m_iRefCnt; }

private:
    int m_iRefCnt;
    friend class CncPositionType;
};

/* construction */
CncPositionTypePrivate::CncPositionTypePrivate()
 : m_iRefCnt(0)
{
    OpcUaCnc_CncPositionType_Initialize(this);
}

/*  Static initializer.
 *  This is used internaly to initialize the static shared_emtpy variable.
 *  RefCnt is set to 1 so it will never be deleted.
 */
CncPositionTypePrivate::CncPositionTypePrivate(bool)
 : m_iRefCnt(1)
{
    OpcUaCnc_CncPositionType_Initialize(this);
}


/*  construction
 */
CncPositionTypePrivate::CncPositionTypePrivate(const OpcUaCnc_CncPositionType &other) // [in] the other OpcUaCnc_CncPositionType.
 : m_iRefCnt(0)
{
    OpcUaCnc_CncPositionType_CopyTo(&other, this);
}

/* destruction */
CncPositionTypePrivate::~CncPositionTypePrivate()
{
    OpcUaCnc_CncPositionType_Clear(this);
}

/*  Add a reference to a CncPositionTypePrivate
 *  @return 0 if the object was deleted - otherwise a value bigger than 0.
 *  This method is not thread save regarding the return value. The returned counter is only reliable when it is 0.
 *  Other values are not reliable and should not be used for any logic.
 */
int CncPositionTypePrivate::addRef()
{
    ua_atomic_increment(&m_iRefCnt);
    return m_iRefCnt;
}

/*  Release a CncPositionTypePrivate.
 *  @return the reference count.
 */
int CncPositionTypePrivate::release()
{
    int currentCount = ua_atomic_decrement(&m_iRefCnt);
    if (currentCount == 0)
    {
        delete this;
    }
    return currentCount;
}

CncPositionTypePrivate* shared_empty_CncPositionType()
{
    static CncPositionTypePrivate shared_static(true);
    return &shared_static;
}


/******************************************************************************
** Class CncPositionType
******************************************************************************/

/** Constructs an instance of the class CncPositionType with empty default values
*/
CncPositionType::CncPositionType()
{
    d_ptr = shared_empty_CncPositionType();
    d_ptr->addRef();
}

/** Constructs an instance of the class CncPositionType with values from another CncPositionType object
 *  @param other the other UaCncPositionType used to initialize the object
 */
CncPositionType::CncPositionType(const CncPositionType &other)
{
    d_ptr = other.d_ptr;
    d_ptr->addRef();
}

/** Constructs an instance of the class CncPositionType with values from another OpcUaCnc_CncPositionType structure
 *  @param other the other OpcUaCnc_CncPositionType used to initialize the object
 */
CncPositionType::CncPositionType(const OpcUaCnc_CncPositionType &other)
{
    d_ptr = new CncPositionTypePrivate(other);
    d_ptr->addRef();
}

/** Constructs an instance of the class CncPositionType with values provided in the constructor
 */
CncPositionType::CncPositionType(
        OpcUa_Double ActPos,
        OpcUa_Double CmdPos,
        OpcUa_Double RemDist
        )
{
    d_ptr = new CncPositionTypePrivate();
    d_ptr->addRef();
    setActPos(ActPos);
    setCmdPos(CmdPos);
    setRemDist(RemDist);
}

/** Constructs an instance of the class CncPositionType initialized with value from a UaExtensionObject
 *  @param extensionObject the extension object containing the CncPositionType
 */
CncPositionType::CncPositionType(const UaExtensionObject &extensionObject)
{
    d_ptr = new CncPositionTypePrivate();
    d_ptr->addRef();

    const OpcUa_ExtensionObject *pExtensionObject = (const OpcUa_ExtensionObject*)extensionObject;
    OpcUaCnc_CncPositionType *pCncPositionType = OPCUACNC_EXTENSIONOBJECT_GET_ENCODEABLE(CncPositionType, pExtensionObject);

    if (pCncPositionType)
    {
        OpcUaCnc_CncPositionType_CopyTo(pCncPositionType, d_ptr);
    }
}

/** Constructs an instance of the class CncPositionType initialized with value from an OpcUa_ExtensionObject structure
 *  @param extensionObject the extension object containing the CncPositionType
 */
CncPositionType::CncPositionType(const OpcUa_ExtensionObject &extensionObject)
{
    d_ptr = new CncPositionTypePrivate();
    d_ptr->addRef();

    OpcUaCnc_CncPositionType *pCncPositionType = OPCUACNC_EXTENSIONOBJECT_GET_ENCODEABLE(CncPositionType, &extensionObject);

    if (pCncPositionType)
    {
        OpcUaCnc_CncPositionType_CopyTo(pCncPositionType, d_ptr);
    }
}

CncPositionType::CncPositionType(UaExtensionObject &extensionObject, OpcUa_Boolean bDetach)
{
    d_ptr = new CncPositionTypePrivate();
    d_ptr->addRef();

    const OpcUa_ExtensionObject *pExtensionObject = (const OpcUa_ExtensionObject*)extensionObject;
    OpcUaCnc_CncPositionType *pCncPositionType = OPCUACNC_EXTENSIONOBJECT_GET_ENCODEABLE(CncPositionType, pExtensionObject);
    if (pCncPositionType)
    {
        if (bDetach == OpcUa_False)
        {
            OpcUaCnc_CncPositionType_CopyTo(pCncPositionType, d_ptr);
        }
        else
        {
            (*(OpcUaCnc_CncPositionType*)d_ptr) = *pCncPositionType;
            OpcUaCnc_CncPositionType_Initialize(pCncPositionType);
            extensionObject.clear();
        }
    }
}

CncPositionType::CncPositionType(OpcUa_ExtensionObject &extensionObject, OpcUa_Boolean bDetach)
{
    d_ptr = new CncPositionTypePrivate();
    d_ptr->addRef();

    OpcUaCnc_CncPositionType *pCncPositionType = OPCUACNC_EXTENSIONOBJECT_GET_ENCODEABLE(CncPositionType, &extensionObject);

    if (pCncPositionType)
    {
        if (bDetach == OpcUa_False)
        {
            OpcUaCnc_CncPositionType_CopyTo(pCncPositionType, d_ptr);
        }
        else
        {
            (*(OpcUaCnc_CncPositionType*)d_ptr) = *pCncPositionType;
            OpcUaCnc_CncPositionType_Initialize(pCncPositionType);
            OpcUa_ExtensionObject_Clear(&extensionObject);
        }
    }
}

/** Destroys the CncPositionType object
*/
CncPositionType::~CncPositionType()
{
    OPCUACNC_D(CncPositionType);
    d->release();
}

/** Clear the data of the CncPositionType.
*/
void CncPositionType::clear()
{
    d_ptr->release();
    d_ptr = shared_empty_CncPositionType();
    d_ptr->addRef();
}

/** Compare two CncPositionType if they are similar.
 *  @param other the CncPositionType to compare.
 *  @return true if similar, false if not.
 */
bool CncPositionType::operator==(const CncPositionType &other) const
{
    return (OpcUaCnc_CncPositionType_Compare(d_ptr, other.d_ptr) == 0);
}

/** Returns true if the other CncPositionType is not equal to this.
 *  @see operator==
 *  @param other the CncPositionType to compare.
 *  @return true if other is not equal to this.
 */
bool CncPositionType::operator!=(const CncPositionType &other) const
{
    return !(operator==(other));
}

/** Assignment operator.
 *  @param other the CncPositionType to assign.
 *  @return Assignment operator.
 */
CncPositionType& CncPositionType::operator=(const CncPositionType &other)
{
    other.d_ptr->addRef();
    d_ptr->release();
    d_ptr = other.d_ptr;
    return *this;
}

/** Copy CncPositionType data to a newly allocated OpcUaCnc_CncPositionType.
 *  @return data to a newly allocated OpcUaCnc_CncPositionType.
 */
OpcUaCnc_CncPositionType* CncPositionType::copy() const
{
    return clone(*d_ptr);
}

/** Copy CncPositionType data to an existing OpcUaCnc_CncPositionType structure.
 *  @param pDst the destination of this copy operation.
 */
void CncPositionType::copyTo(OpcUaCnc_CncPositionType *pDst) const
{
    if (pDst == OpcUa_Null) return;
    cloneTo(*d_ptr, *pDst);
}

/** Copy OpcUaCnc_CncPositionType data to a newly allocated OpcUaCnc_CncPositionType.
 *  @param source Source to clone.
 *  @return new copy.
 */
OpcUaCnc_CncPositionType* CncPositionType::clone(const OpcUaCnc_CncPositionType& source)
{
    OpcUaCnc_CncPositionType* pCncPositionType = OpcUa_Null;
    OpcUaCnc_CncPositionType_Copy(&source, &pCncPositionType);
    return pCncPositionType;
}

/** Copy OpcUaCnc_CncPositionType data to an existing OpcUaCnc_CncPositionType structure.
 *  @param source the source of the clone operation.
 *  @param copy the destination of the clone operation.
 */
void CncPositionType::cloneTo(const OpcUaCnc_CncPositionType& source, OpcUaCnc_CncPositionType& copy)
{
    OpcUaCnc_CncPositionType_CopyTo(&source, &copy);
}

/** Attaches the data of the parameter pValue.
 * Don't clear the data of pValue afterwards manually, because CncPositionType is responsible for it now.
 */
void CncPositionType::attach(const OpcUaCnc_CncPositionType *pValue) //!< [in] Parameter to attach to.
{
    if (pValue == OpcUa_Null) return;
    if (d_ptr->refCount() == 1)
    {
        OpcUaCnc_CncPositionType_Clear(d_ptr);
    }
    else
    {
        d_ptr->release();
        d_ptr = new CncPositionTypePrivate();
        d_ptr->addRef();
    }
    // copy data value structure (no deep copy)
    OpcUa_MemCpy(d_ptr, sizeof(OpcUaCnc_CncPositionType), (void*)pValue, sizeof(OpcUaCnc_CncPositionType));
}

/** Detaches the internal CncPositionType structure from this class.
 *  This way you take over the control of releasing the CncPositionType data.
 *  If more than one references exist, the data is copied to pDst instead of being detached.
 *  @return If the functions succeeds pDst is returned, otherwise 0 is returned.
 */
OpcUaCnc_CncPositionType* CncPositionType::detach(OpcUaCnc_CncPositionType* pDst) //!< [out] Pointer to OpcUaCnc_CncPositionType structure that receives the CncPositionType data.
{
    if (pDst == OpcUa_Null) return OpcUa_Null;
    if (d_ptr->refCount() == 1)
    {
        OpcUa_MemCpy(pDst, sizeof(OpcUaCnc_CncPositionType), d_ptr, sizeof(OpcUaCnc_CncPositionType));
        // clear internal data without releasing deeper memory
        OpcUaCnc_CncPositionType_Initialize(d_ptr);
    }
    else
    {
        OpcUaCnc_CncPositionType_CopyTo(d_ptr, pDst);
    }
    d_ptr->release();
    d_ptr = shared_empty_CncPositionType();
    d_ptr->addRef();
    return pDst;
}

void CncPositionType::toVariant(UaVariant &variant) const
{
    UaExtensionObject extensionObject;
    toExtensionObject(extensionObject);
    variant.setExtensionObject(extensionObject, OpcUa_True);
}

void CncPositionType::toVariant(OpcUa_Variant &variant) const
{
    OpcUa_Variant_Clear(&variant);
    variant.Datatype = OpcUaType_ExtensionObject;
    variant.ArrayType = OpcUa_VariantArrayType_Scalar;
    variant.Value.ExtensionObject = (OpcUa_ExtensionObject*)OpcUa_Alloc(sizeof(OpcUa_ExtensionObject));
    OpcUa_ExtensionObject_Initialize(variant.Value.ExtensionObject);
    toExtensionObject(*variant.Value.ExtensionObject);
}

void CncPositionType::toVariant(UaVariant &variant, OpcUa_Boolean bDetach)
{
    UaExtensionObject extensionObject;
    toExtensionObject(extensionObject, bDetach);
    variant.setExtensionObject(extensionObject, OpcUa_True);
}

void CncPositionType::toVariant(OpcUa_Variant &variant, OpcUa_Boolean bDetach)
{
    OpcUa_Variant_Clear(&variant);
    variant.Datatype = OpcUaType_ExtensionObject;
    variant.ArrayType = OpcUa_VariantArrayType_Scalar;
    variant.Value.ExtensionObject = (OpcUa_ExtensionObject*)OpcUa_Alloc(sizeof(OpcUa_ExtensionObject));
    OpcUa_ExtensionObject_Initialize(variant.Value.ExtensionObject);
    toExtensionObject(*variant.Value.ExtensionObject, bDetach);
}

void CncPositionType::toDataValue(UaDataValue &dataValue, OpcUa_Boolean updateTimeStamps) const
{
    UaVariant variant;
    toVariant(variant);
    dataValue.setValue(variant, OpcUa_True, updateTimeStamps);
}

void CncPositionType::toDataValue(OpcUa_DataValue &dataValue, OpcUa_Boolean updateTimeStamps) const
{
    OpcUa_Variant_Clear(&dataValue.Value);
    dataValue.Value.Datatype = OpcUaType_ExtensionObject;
    dataValue.Value.ArrayType = OpcUa_VariantArrayType_Scalar;
    dataValue.Value.Value.ExtensionObject = (OpcUa_ExtensionObject*)OpcUa_Alloc(sizeof(OpcUa_ExtensionObject));
    OpcUa_ExtensionObject_Initialize(dataValue.Value.Value.ExtensionObject);
    toExtensionObject(*dataValue.Value.Value.ExtensionObject);

    if (updateTimeStamps != OpcUa_False)
    {
        dataValue.SourceTimestamp = OpcUa_DateTime_UtcNow();
        dataValue.ServerTimestamp = OpcUa_DateTime_UtcNow();
    }
}

void CncPositionType::toDataValue(UaDataValue &dataValue, OpcUa_Boolean bDetach, OpcUa_Boolean updateTimeStamps)
{
    UaVariant variant;
    toVariant(variant, bDetach);
    dataValue.setValue(variant, OpcUa_True, updateTimeStamps);
}

void CncPositionType::toDataValue(OpcUa_DataValue &dataValue, OpcUa_Boolean bDetach, OpcUa_Boolean updateTimeStamps)
{
    OpcUa_Variant_Clear(&dataValue.Value);
    dataValue.Value.Datatype = OpcUaType_ExtensionObject;
    dataValue.Value.ArrayType = OpcUa_VariantArrayType_Scalar;
    dataValue.Value.Value.ExtensionObject = (OpcUa_ExtensionObject*)OpcUa_Alloc(sizeof(OpcUa_ExtensionObject));
    OpcUa_ExtensionObject_Initialize(dataValue.Value.Value.ExtensionObject);
    toExtensionObject(*dataValue.Value.Value.ExtensionObject, bDetach);

    if (updateTimeStamps != OpcUa_False)
    {
        dataValue.SourceTimestamp = OpcUa_DateTime_UtcNow();
        dataValue.ServerTimestamp = OpcUa_DateTime_UtcNow();
    }
}

void CncPositionType::toExtensionObject(UaExtensionObject &extensionObject) const
{
    OpcUa_ExtensionObject *pExtensionObject = (OpcUa_ExtensionObject*)(const OpcUa_ExtensionObject*)extensionObject;
    toExtensionObject(*pExtensionObject);
}

void CncPositionType::toExtensionObject(OpcUa_ExtensionObject &extensionObject) const
{
    OpcUa_ExtensionObject_Clear(&extensionObject);
    OpcUaCnc_CncPositionType *pCncPositionType = OpcUa_Null;
    if (OpcUa_IsGood(OpcUa_EncodeableObject_CreateExtension(&OpcUaCnc_CncPositionType_EncodeableType,
                                                            &extensionObject,
                                                            (OpcUa_Void**)&pCncPositionType)))
    {
        OpcUaCnc_CncPositionType_CopyTo(d_ptr, pCncPositionType);
    }
}

void CncPositionType::toExtensionObject(UaExtensionObject &extensionObject, OpcUa_Boolean bDetach)
{
    OpcUa_ExtensionObject *pExtensionObject = (OpcUa_ExtensionObject*)(const OpcUa_ExtensionObject*)extensionObject;
    toExtensionObject(*pExtensionObject, bDetach);
}

void CncPositionType::toExtensionObject(OpcUa_ExtensionObject &extensionObject, OpcUa_Boolean bDetach)
{
    OpcUa_ExtensionObject_Clear(&extensionObject);
    OpcUaCnc_CncPositionType *pCncPositionType = OpcUa_Null;
    if (OpcUa_IsGood(OpcUa_EncodeableObject_CreateExtension(&OpcUaCnc_CncPositionType_EncodeableType,
                                                            &extensionObject,
                                                            (OpcUa_Void**)&pCncPositionType)))
    {
        OpcUaCnc_CncPositionType_Initialize(pCncPositionType);
        if (bDetach != OpcUa_False && d_ptr->refCount() == 1)
        {
            *pCncPositionType = *d_ptr;
            // clear internal data without releasing deeper memory
            OpcUaCnc_CncPositionType_Initialize(d_ptr);
        }
        else
        {
            OpcUaCnc_CncPositionType_CopyTo(d_ptr, pCncPositionType);
        }
        if (bDetach != OpcUa_False)
        {
            d_ptr->release();
            d_ptr = shared_empty_CncPositionType();
            d_ptr->addRef();
        }
    }
}

OpcUa_StatusCode CncPositionType::setCncPositionType(const UaExtensionObject &extensionObject)
{
    OpcUa_ExtensionObject *pExtensionObject = (OpcUa_ExtensionObject*)(const OpcUa_ExtensionObject*)extensionObject;
    return setCncPositionType(*pExtensionObject);
}

OpcUa_StatusCode CncPositionType::setCncPositionType(const OpcUa_ExtensionObject &extensionObject)
{
    OpcUa_StatusCode ret = OpcUa_BadTypeMismatch;
    OpcUaCnc_CncPositionType *pCncPositionType = OPCUACNC_EXTENSIONOBJECT_GET_ENCODEABLE(CncPositionType, &extensionObject);

    if (pCncPositionType)
    {
        ret = OpcUa_Good;

        if (d_ptr->refCount() == 1)
        {
            OpcUaCnc_CncPositionType_Clear(d_ptr);
        }
        else
        {
            d_ptr->release();
            d_ptr = new CncPositionTypePrivate();
            d_ptr->addRef();
        }

        OpcUaCnc_CncPositionType_CopyTo(pCncPositionType, d_ptr);
    }
    return ret;
}

OpcUa_StatusCode CncPositionType::setCncPositionType(UaExtensionObject &extensionObject, OpcUa_Boolean bDetach)
{
    OpcUa_ExtensionObject *pExtensionObject = (OpcUa_ExtensionObject*)(const OpcUa_ExtensionObject*)extensionObject;
    return setCncPositionType(*pExtensionObject, bDetach);
}

OpcUa_StatusCode CncPositionType::setCncPositionType(OpcUa_ExtensionObject &extensionObject, OpcUa_Boolean bDetach)
{
    OpcUa_StatusCode ret = OpcUa_BadTypeMismatch;
    OpcUaCnc_CncPositionType *pCncPositionType = OPCUACNC_EXTENSIONOBJECT_GET_ENCODEABLE(CncPositionType, &extensionObject);

    if (pCncPositionType != OpcUa_Null)
    {
        ret = OpcUa_Good;

        if (d_ptr->refCount() == 1)
        {
            OpcUaCnc_CncPositionType_Clear(d_ptr);
        }
        else
        {
            d_ptr->release();
            d_ptr = new CncPositionTypePrivate();
            d_ptr->addRef();
        }

        if (bDetach == OpcUa_False)
        {
            OpcUaCnc_CncPositionType_CopyTo(pCncPositionType, d_ptr);
        }
        else
        {
            (*(OpcUaCnc_CncPositionType*)d_ptr) = *pCncPositionType;
            OpcUaCnc_CncPositionType_Initialize(pCncPositionType);
            OpcUa_ExtensionObject_Clear(&extensionObject);
        }
    }
    return ret;
}

void CncPositionType::setCncPositionType(
        OpcUa_Double ActPos,
        OpcUa_Double CmdPos,
        OpcUa_Double RemDist
        )
{
    if (d_ptr->refCount() == 1)
    {
        OpcUaCnc_CncPositionType_Clear(d_ptr);
    }
    else
    {
        d_ptr->release();
        d_ptr = new CncPositionTypePrivate();
        d_ptr->addRef();
    }
    setActPos(ActPos);
    setCmdPos(CmdPos);
    setRemDist(RemDist);
}

OpcUa_Double CncPositionType::getActPos() const
{
    return d_ptr->ActPos;
}

OpcUa_Double CncPositionType::getCmdPos() const
{
    return d_ptr->CmdPos;
}

OpcUa_Double CncPositionType::getRemDist() const
{
    return d_ptr->RemDist;
}

void CncPositionType::setActPos(OpcUa_Double ActPos)
{
    if (d_ptr->refCount() > 1)
    {
        CncPositionTypePrivate *pNew = new CncPositionTypePrivate((const OpcUaCnc_CncPositionType)*d_ptr);
        d_ptr->release();
        d_ptr = pNew;
        d_ptr->addRef();
    }

    d_ptr->ActPos = ActPos;
}

void CncPositionType::setCmdPos(OpcUa_Double CmdPos)
{
    if (d_ptr->refCount() > 1)
    {
        CncPositionTypePrivate *pNew = new CncPositionTypePrivate((const OpcUaCnc_CncPositionType)*d_ptr);
        d_ptr->release();
        d_ptr = pNew;
        d_ptr->addRef();
    }

    d_ptr->CmdPos = CmdPos;
}

void CncPositionType::setRemDist(OpcUa_Double RemDist)
{
    if (d_ptr->refCount() > 1)
    {
        CncPositionTypePrivate *pNew = new CncPositionTypePrivate((const OpcUaCnc_CncPositionType)*d_ptr);
        d_ptr->release();
        d_ptr = pNew;
        d_ptr->addRef();
    }

    d_ptr->RemDist = RemDist;
}


/******************************************************************************
** Class CncPositionTypes
******************************************************************************/
CncPositionTypes CncPositionTypes::empty;

CncPositionTypes::CncPositionTypes()
: m_noOfElements(0),
  m_data((OpcUaCnc_CncPositionType*)OpcUa_Null)
{
}

CncPositionTypes::CncPositionTypes(const CncPositionTypes &other)
: m_noOfElements(0),
  m_data((OpcUaCnc_CncPositionType*)OpcUa_Null)
{
    operator=(other);
}

CncPositionTypes::CncPositionTypes(OpcUa_Int32 length, OpcUaCnc_CncPositionType* data)
: m_noOfElements(0),
  m_data((OpcUaCnc_CncPositionType*)OpcUa_Null)
{
    if (length > 0 && data != OpcUa_Null)
    {
        m_noOfElements = length;
        m_data = (OpcUaCnc_CncPositionType*)OpcUa_Alloc(m_noOfElements * sizeof(OpcUaCnc_CncPositionType));
        for (OpcUa_UInt32 i = 0; i < m_noOfElements; i++)
        {
            OpcUaCnc_CncPositionType_CopyTo(&(data[i]), &(m_data[i]));
        }
    }
}

CncPositionTypes::~CncPositionTypes()
{
    clear();
}

CncPositionTypes& CncPositionTypes::operator=(const CncPositionTypes &other)
{
    if (this == &other) {return *this;}

    clear();
    if (other.m_noOfElements > 0)
    {
        m_noOfElements = other.m_noOfElements;
        m_data = (OpcUaCnc_CncPositionType*)OpcUa_Alloc(m_noOfElements * sizeof(OpcUaCnc_CncPositionType));
        for (OpcUa_UInt32 i = 0; i < m_noOfElements; i++)
        {
            OpcUaCnc_CncPositionType_CopyTo(&(other.m_data[i]), &(m_data[i]));
        }
    }
    return *this;
}

/** Returns the OpcUaCnc_CncPositionType at index position index as a modifiable reference.
 *
 *  index must be valid index position in the array.
 */
OpcUaCnc_CncPositionType& CncPositionTypes::operator[](OpcUa_UInt32 index)
{
    assert(index<m_noOfElements);
    return m_data[index];
}

/** Returns the OpcUaCnc_CncPositionType at index position index.
 *
 *  index must be valid index position in the array.
 */
const OpcUaCnc_CncPositionType& CncPositionTypes::operator[](OpcUa_UInt32 index) const
{
    assert(index<m_noOfElements);
    return m_data[index];
}

/** Attaches the raw data.
 *
 *  Clears the array and takes the ownership of data.
 *  Don't clear the data afterwards manually, because CncPositionTypes is responsible for it now.
 */
void CncPositionTypes::attach(OpcUa_UInt32 length, OpcUaCnc_CncPositionType* data)
{
    clear();
    m_data = data;
    m_noOfElements = length;
}

/** Attaches the raw data.
 *
 *  Clears the array and takes the ownership of data.
 *  Don't clear the data afterwards manually, because CncPositionTypes is responsible for it now.
 */
void CncPositionTypes::attach(OpcUa_Int32 length, OpcUaCnc_CncPositionType* data)
{
    clear();
    if (length >= 0)
    {
        m_data = data;
        m_noOfElements = length;
    }
}

bool CncPositionTypes::operator==(const CncPositionTypes &other) const
{
    if (m_noOfElements != other.m_noOfElements) {return false;}

    if (m_noOfElements > 0)
    {
        for (OpcUa_UInt32 i = 0; i < m_noOfElements; i++)
        {
            if (OpcUaCnc_CncPositionType_Compare(&(m_data[i]), &(other.m_data[i])) != OPCUA_EQUAL) {return false;};
        }
    }
    return true;
}

bool CncPositionTypes::operator!=(const CncPositionTypes &other) const
{
    return !(operator==(other));
}

/** Detaches the raw data from this class.
 *
 *  The caller takes ownership of the raw data and is responsible for deleting it
 *  by calling OpcUa_Free.
 *  @return The raw data.
 */
OpcUaCnc_CncPositionType* CncPositionTypes::detach()
{
    OpcUaCnc_CncPositionType* pRet = m_data;
    m_noOfElements = 0;
    m_data = (OpcUaCnc_CncPositionType*)OpcUa_Null;
    return pRet;
}

void CncPositionTypes::create(OpcUa_UInt32 length)
{
    clear();
    if (length > 0)
    {
        m_data = (OpcUaCnc_CncPositionType*)OpcUa_Alloc(length * sizeof(OpcUaCnc_CncPositionType));
        for (OpcUa_UInt32 i = 0; i < length; i++)
        {
            OpcUaCnc_CncPositionType_Initialize(&(m_data[i]));
        }
        m_noOfElements = length;
    }
}

void CncPositionTypes::resize(OpcUa_UInt32 length)
{
    if (length < m_noOfElements)
    {
        if (length != 0)
        {
            for (OpcUa_UInt32 i = length; i < m_noOfElements; i++)
            {
                OpcUaCnc_CncPositionType_Clear(&(m_data[i]));
            }

            OpcUaCnc_CncPositionType* newData = (OpcUaCnc_CncPositionType*)OpcUa_ReAlloc(m_data, length * sizeof(OpcUaCnc_CncPositionType));
            if (newData)
            {
                m_data = newData;
                m_noOfElements = length;
            }
        }
        else
        {
            clear();
        }
    }
    else if (length > m_noOfElements)
    {
        OpcUaCnc_CncPositionType* newData = (OpcUaCnc_CncPositionType*)OpcUa_ReAlloc(m_data, length * sizeof(OpcUaCnc_CncPositionType));
        if (newData)
        {
            for (OpcUa_UInt32 i = m_noOfElements; i < length; i++)
            {
                OpcUaCnc_CncPositionType_Initialize(&(newData[i]));
            }
            m_data = newData;
            m_noOfElements = length;
        }
    }
}

void CncPositionTypes::clear()
{
    if (m_data)
    {
        for (OpcUa_UInt32 i = 0; i < m_noOfElements; i++)
        {
            OpcUaCnc_CncPositionType_Clear(&(m_data[i]));
        }
        OpcUa_Free(m_data);
        m_data = (OpcUaCnc_CncPositionType*)OpcUa_Null;
    }
    m_noOfElements = 0;
}

void CncPositionTypes::toVariant(UaVariant &variant) const
{
    OpcUa_Variant *pVariant = (OpcUa_Variant*)(const OpcUa_Variant*)variant;
    toVariant(*pVariant);
}

void CncPositionTypes::toVariant(OpcUa_Variant &variant) const
{
    OpcUa_Variant_Clear(&variant);

    variant.Datatype = OpcUaType_ExtensionObject;
    variant.ArrayType = OpcUa_VariantArrayType_Array;
    variant.Value.Array.Length = m_noOfElements;
    variant.Value.Array.Value.ExtensionObjectArray = (OpcUa_ExtensionObject*)OpcUa_Alloc(m_noOfElements * sizeof(OpcUa_ExtensionObject));
    for (OpcUa_UInt32 i = 0; i < m_noOfElements; i++)
    {
        OpcUaCnc_CncPositionType *pValue = OpcUa_Null;
        OpcUa_ExtensionObject_Initialize(&variant.Value.Array.Value.ExtensionObjectArray[i]);
        OpcUa_EncodeableObject_CreateExtension(&OpcUaCnc_CncPositionType_EncodeableType,
                                               &variant.Value.Array.Value.ExtensionObjectArray[i],
                                               (OpcUa_Void**)&pValue);
        OpcUaCnc_CncPositionType_CopyTo(&m_data[i], pValue);
    }
}

void CncPositionTypes::toVariant(UaVariant &variant, OpcUa_Boolean bDetach)
{
    OpcUa_Variant *pVariant = (OpcUa_Variant*)(const OpcUa_Variant*)variant;
    toVariant(*pVariant, bDetach);
}

void CncPositionTypes::toVariant(OpcUa_Variant &variant, OpcUa_Boolean bDetach)
{
    OpcUa_Variant_Clear(&variant);
    variant.Datatype = OpcUaType_ExtensionObject;
    variant.ArrayType = OpcUa_VariantArrayType_Array;
    variant.Value.Array.Length = m_noOfElements;
    variant.Value.Array.Value.ExtensionObjectArray = (OpcUa_ExtensionObject*)OpcUa_Alloc(m_noOfElements * sizeof(OpcUa_ExtensionObject));
    for (OpcUa_UInt32 i = 0; i < m_noOfElements; i++)
    {
        OpcUaCnc_CncPositionType *pValue = OpcUa_Null;
        OpcUa_ExtensionObject_Initialize(&variant.Value.Array.Value.ExtensionObjectArray[i]);
        OpcUa_EncodeableObject_CreateExtension(&OpcUaCnc_CncPositionType_EncodeableType,
                                               &variant.Value.Array.Value.ExtensionObjectArray[i],
                                               (OpcUa_Void**)&pValue);
        if (bDetach != OpcUa_False)
        {
            *pValue = m_data[i];
        }
        else
        {
            OpcUaCnc_CncPositionType_CopyTo(&m_data[i], pValue);
        }
    }
    if (bDetach != OpcUa_False)
    {
        OpcUa_Free(m_data);
        m_data = (OpcUaCnc_CncPositionType*)OpcUa_Null;
        m_noOfElements = 0;
    }
}

void CncPositionTypes::toDataValue(UaDataValue &dataValue, OpcUa_Boolean updateTimeStamps) const
{
    UaVariant variant;
    toVariant(variant);
    dataValue.setValue(variant, OpcUa_True, updateTimeStamps);
}

void CncPositionTypes::toDataValue(OpcUa_DataValue &dataValue, OpcUa_Boolean updateTimeStamps) const
{
    toVariant(dataValue.Value);

    if (updateTimeStamps != OpcUa_False)
    {
        dataValue.SourceTimestamp = OpcUa_DateTime_UtcNow();
        dataValue.ServerTimestamp = OpcUa_DateTime_UtcNow();
    }
}

void CncPositionTypes::toDataValue(UaDataValue &dataValue, OpcUa_Boolean bDetach, OpcUa_Boolean updateTimeStamps)
{
    UaVariant variant;
    toVariant(variant, bDetach);
    dataValue.setValue(variant, OpcUa_True, updateTimeStamps);
}

void CncPositionTypes::toDataValue(OpcUa_DataValue &dataValue, OpcUa_Boolean bDetach, OpcUa_Boolean updateTimeStamps)
{
    toVariant(dataValue.Value, bDetach);

    if (updateTimeStamps != OpcUa_False)
    {
        dataValue.SourceTimestamp = OpcUa_DateTime_UtcNow();
        dataValue.ServerTimestamp = OpcUa_DateTime_UtcNow();
    }
}

OpcUa_StatusCode CncPositionTypes::setCncPositionTypes(const UaVariant &variant)
{
    OpcUa_Variant *pVariant = (OpcUa_Variant*)(const OpcUa_Variant*)variant;
    return setCncPositionTypes(*pVariant);
}

OpcUa_StatusCode CncPositionTypes::setCncPositionTypes(const OpcUa_Variant &variant)
{
    return setCncPositionTypes((OpcUa_Variant&)variant, OpcUa_False);
}

OpcUa_StatusCode CncPositionTypes::setCncPositionTypes(UaVariant &variant, OpcUa_Boolean bDetach)
{
    OpcUa_Variant *pVariant = (OpcUa_Variant*)(const OpcUa_Variant*)variant;
    return setCncPositionTypes(*pVariant, bDetach);
}

OpcUa_StatusCode CncPositionTypes::setCncPositionTypes(OpcUa_Variant &variant, OpcUa_Boolean bDetach)
{
    clear();

    OpcUa_StatusCode ret = OpcUa_BadTypeMismatch;
    if (variant.Datatype == OpcUaType_ExtensionObject &&
        variant.ArrayType == OpcUa_VariantArrayType_Array)
    {
        ret = OpcUa_Good;
        m_noOfElements = variant.Value.Array.Length >= 0 ? variant.Value.Array.Length : 0;
        if (m_noOfElements > 0 && variant.Value.Array.Value.ExtensionObjectArray != OpcUa_Null)
        {
            m_data = (OpcUaCnc_CncPositionType*)OpcUa_Alloc(m_noOfElements * sizeof(OpcUaCnc_CncPositionType));

            OpcUa_UInt32 i = 0;
            for (i = 0; i < m_noOfElements; i++)
            {
                OpcUaCnc_CncPositionType_Initialize(&m_data[i]);

                OpcUaCnc_CncPositionType *pValue = OPCUACNC_EXTENSIONOBJECT_GET_ENCODEABLE(CncPositionType, &variant.Value.Array.Value.ExtensionObjectArray[i]);
                if (pValue)
                {
                    if (bDetach != OpcUa_False)
                    {
                        m_data[i] = *pValue;
                        OpcUaCnc_CncPositionType_Initialize(pValue);
                    }
                    else
                    {
                        OpcUaCnc_CncPositionType_CopyTo(pValue, &m_data[i]);
                    }
                }
                else
                {
                    ret = OpcUa_BadTypeMismatch;
                    break;
                }
            }
            if (OpcUa_IsNotGood(ret))
            {
                for (OpcUa_UInt32 j = 0; j < i; j++)
                {
                    OpcUaCnc_CncPositionType_Clear(&m_data[j]);
                }
                OpcUa_Free(m_data);
                m_data = (OpcUaCnc_CncPositionType*)OpcUa_Null;
                m_noOfElements = 0;
            }
        }
        else
        {
            m_noOfElements = 0;
        }
    }
    return ret;
}

OpcUa_StatusCode CncPositionTypes::setCncPositionTypes(OpcUa_Int32 length, OpcUaCnc_CncPositionType* data)
{
    clear();

    if (length > 0 && data != OpcUa_Null)
    {
        m_noOfElements = length;
        m_data = (OpcUaCnc_CncPositionType*)OpcUa_Alloc(m_noOfElements * sizeof(OpcUaCnc_CncPositionType));
        for (OpcUa_UInt32 i = 0; i < m_noOfElements; i++)
        {
            OpcUaCnc_CncPositionType_CopyTo(&(data[i]), &(m_data[i]));
        }
    }
    return OpcUa_Good;
}

} // namespace OpcUaCnc

