/******************************************************************************
** opcuacnc_cncalarmtypebase.h
**
**   **************************** auto-generated ****************************
**     This code was generated by a tool: UaModeler
**     Runtime Version: 1.5.0, using C++ OPC UA SDK 1.5.0 template (version 4)
**
**     Changes to this file may cause incorrect behavior and will be lost if
**     the code is regenerated.
**   **************************** auto-generated ****************************
**
** Copyright (c) 2006-2016 Unified Automation GmbH. All rights reserved.
**
** Software License Agreement ("SLA") Version 2.5
**
** Unless explicitly acquired and licensed from Licensor under another
** license, the contents of this file are subject to the Software License
** Agreement ("SLA") Version 2.5, or subsequent versions
** as allowed by the SLA, and You may not copy or use this file in either
** source code or executable form, except in compliance with the terms and
** conditions of the SLA.
**
** All software distributed under the SLA is provided strictly on an
** "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED,
** AND LICENSOR HEREBY DISCLAIMS ALL SUCH WARRANTIES, INCLUDING WITHOUT
** LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
** PURPOSE, QUIET ENJOYMENT, OR NON-INFRINGEMENT. See the SLA for specific
** language governing rights and limitations under the SLA.
**
** The complete license agreement can be found here:
** http://unifiedautomation.com/License/SLA/2.5/
**
** Project: C++ OPC Server SDK information model for namespace http://opcfoundation.org/UA/CNC/
**
** Description: OPC Unified Architecture Software Development Kit.
**
** Created: 19.08.2016
**
******************************************************************************/

#ifndef __OPCUACNC_CNCALARMTYPEBASE_H__
#define __OPCUACNC_CNCALARMTYPEBASE_H__

#include "opcua_discretealarmtype.h"
#include "opcuacnc_datatypes.h"
#include "basenodes.h"
#include "opcua_propertytype.h"
#include "opcuacnc_datatypes.h"
#include "opcuacnc_identifiers.h"
#include "opcuacnc_instancefactory_cnc.h"

// Namespace for the UA information model http://opcfoundation.org/UA/CNC/
namespace OpcUaCnc {

class CncAlarmTypeBase;

/** Generated event data class for a CncAlarmType.
 *
 *  This class contains the auto generated code for the object type CncAlarmType
 *  providing UaEventData interface for the access to event data containing the current state of the
 *  condition for events sent to the client. The class is used for condition events if the condition has
 *  no nodes in the address space or for condition branches created as snapshot of the main branch.
 *
 *  **Event Fields of the CncAlarmType:**
 *
 *  Browse Name     | DataType | TypeDefinition | Modelling Rule | See Also
 *  ----------------|----------|----------------|----------------|-------------------------------------------------
 *  AlarmIdentifier | String   | PropertyType   | Mandatory      | \ref getAlarmIdentifier, \ref setAlarmIdentifier
 *  AuxParameters   | String   | PropertyType   | Optional       | \ref getAuxParameters, \ref setAuxParameters
 *  HelpSource      | String   | PropertyType   | Optional       | \ref getHelpSource, \ref setHelpSource

 */
class UAMODELS_EXPORT CncAlarmTypeData:
    public OpcUa::DiscreteAlarmTypeData
{
    UA_DISABLE_COPY(CncAlarmTypeData);
protected:
    virtual ~CncAlarmTypeData();
public:
    CncAlarmTypeData();
    void initializeAsBranch(CncAlarmTypeBase* pCondition);
    void initializeAsBranch(CncAlarmTypeData* pConditionData);
    virtual void getFieldData(OpcUa_UInt32 index, Session* pSession, OpcUa_Variant& data);
    // AlarmIdentifier
    void setAlarmIdentifier(const UaString& AlarmIdentifier);
    void setAlarmIdentifierStatus(OpcUa_StatusCode status);
    UaString getAlarmIdentifier();
    virtual void getAlarmIdentifierValue(Session* pSession, OpcUa_Variant& value);
    // AuxParameters
    void setAuxParameters(const UaString& AuxParameters);
    void setAuxParametersStatus(OpcUa_StatusCode status);
    UaString getAuxParameters();
    virtual void getAuxParametersValue(Session* pSession, OpcUa_Variant& value);
    // HelpSource
    void setHelpSource(const UaString& HelpSource);
    void setHelpSourceStatus(OpcUa_StatusCode status);
    UaString getHelpSource();
    virtual void getHelpSourceValue(Session* pSession, OpcUa_Variant& value);


private:
    void initialize();

private:
    UaObjectPointerArray<UaVariant> m_FieldValues;
};


/** Generated base class for a CncAlarmType.
 *
 *  This class contains the auto generated code for the object type CncAlarmType
 *  representing an OPC UA condition type. This class is used to create the condition type and to
 *  create and represent the condition object in the server address space. It provides also the UaEventData
 *  interface for the access to event data containing the current state of the condition for events sent to
 *  the client.
 *
 *  **Variable members of the CncAlarmType:**
 *
 *  Browse Name     | DataType | TypeDefinition | Modelling Rule | See Also
 *  ----------------|----------|----------------|----------------|-------------------------------------------------
 *  AlarmIdentifier | String   | PropertyType   | Mandatory      | \ref getAlarmIdentifier, \ref setAlarmIdentifier
 *  AuxParameters   | String   | PropertyType   | Optional       | \ref getAuxParameters, \ref setAuxParameters
 *  HelpSource      | String   | PropertyType   | Optional       | \ref getHelpSource, \ref setHelpSource
 *
 */
class UAMODELS_EXPORT CncAlarmTypeBase:
    public OpcUa::DiscreteAlarmType
{
    friend class CncAlarmTypeData;
    UA_DISABLE_COPY(CncAlarmTypeBase);
protected:
    // destruction
    virtual ~CncAlarmTypeBase();
public:
    // construction
    CncAlarmTypeBase(const UaNodeId& nodeId, UaObject* pInstanceDeclarationObject, NodeManagerConfig* pNodeConfig, const UaNodeId& sourceNode, const UaString& sourceName, UaMutexRefCounted* pSharedMutex = NULL);
    CncAlarmTypeBase(const UaNodeId& nodeId, const UaString& name, OpcUa_UInt16 browseNameNameSpaceIndex, NodeManagerConfig* pNodeConfig, const UaNodeId& sourceNode, const UaString& sourceName, UaMutexRefCounted* pSharedMutex = NULL);
    CncAlarmTypeBase(
        UaBase::Object*    pBaseNode,
        XmlUaNodeFactoryManager*   pFactory,
        NodeManagerConfig* pNodeConfig,
        UaMutexRefCounted* pSharedMutex = NULL);

    static void createTypes();
    static void clearStaticMembers();
    virtual UaNodeId typeDefinitionId() const;
    static void registerEventFields();
    static OpcUa_UInt32 registerOptionalEventFields(const UaString& fieldName);
    virtual void getFieldData(OpcUa_UInt32 index, Session* pSession, OpcUa_Variant& data);
    void clearFieldData();
    UaNodeId createBranch();


    // AlarmIdentifier
    virtual void setAlarmIdentifier(const UaString& AlarmIdentifier);
    virtual UaString getAlarmIdentifier() const;
    virtual void setAlarmIdentifierStatus(OpcUa_StatusCode status);
    virtual void getAlarmIdentifierValue(Session* pSession, UaVariant& value);
    // AuxParameters
    virtual void setAuxParameters(const UaString& AuxParameters);
    virtual UaString getAuxParameters() const;
    virtual void setAuxParametersStatus(OpcUa_StatusCode status);
    virtual void getAuxParametersValue(Session* pSession, UaVariant& value);
    // HelpSource
    virtual void setHelpSource(const UaString& HelpSource);
    virtual UaString getHelpSource() const;
    virtual void setHelpSourceStatus(OpcUa_StatusCode status);
    virtual void getHelpSourceValue(Session* pSession, UaVariant& value);

    virtual OpcUa::PropertyType* getAlarmIdentifierNode();
    virtual const OpcUa::PropertyType* getAlarmIdentifierNode() const;
    virtual OpcUa::PropertyType* getAuxParametersNode();
    virtual const OpcUa::PropertyType* getAuxParametersNode() const;
    virtual OpcUa::PropertyType* getHelpSourceNode();
    virtual const OpcUa::PropertyType* getHelpSourceNode() const;

    // NodeAccessInfo management
    virtual void useAccessInfoFromType();
    void useAccessInfoFromInstance(CncAlarmTypeBase *pInstance);

    virtual UaStatus triggerEvent(
        const UaDateTime&   time,
        const UaDateTime&   receiveTime,
        const UaByteString& eventId);

    virtual void getCncAlarmTypeOptionalFieldData(OpcUa_UInt32 index, Session* pSession, OpcUa_Variant& data);

protected:
    // Variable nodes
    // Variable AlarmIdentifier
    static OpcUa::PropertyType*  s_pAlarmIdentifier;
    OpcUa::PropertyType*  m_pAlarmIdentifier;
    // Variable AuxParameters
    static OpcUa::PropertyType*  s_pAuxParameters;
    OpcUa::PropertyType*  m_pAuxParameters;
    // Variable HelpSource
    static OpcUa::PropertyType*  s_pHelpSource;
    OpcUa::PropertyType*  m_pHelpSource;



private:
    void initialize();
    void createChildren();

private:
    static bool                                 s_typeNodesCreated;
    static std::map<OpcUa_UInt32, OpcUa_UInt32> s_CncAlarmTypeDataFields;
    UaObjectPointerArray<UaVariant>             m_FieldValues;
};

} // End namespace for the UA information model http://opcfoundation.org/UA/CNC/

#endif // #ifndef __OPCUACNCCNCALARMTYPEBASE_H__

